import bcrypt from 'bcryptjs';import {db,rows,one,insert,update,transaction,num,money,ident,meta,json,type DB,type Row} from './db';import {requireRole} from './auth';import {register,verifyCode,issueCode,changePassword,email,password} from './accounts';import {assert,qty,notice,refreshStock,notify,releaseHold,history} from './operations';import {standardCheckout,paymentOutcome,retryPayment,advance,bookDelivery,trackDelivery,confirmPaid} from './commerce';import {enroll,defer} from './subscriptions';import {cakeRequest,quoteCake,acceptCake} from './cakes';import {now,businessDate,settings,configure,readOutbox} from './runtime';import {jobs} from './jobs';import {marketingGateway,courierGateway} from './integrations';
export const editable=['Category','Product','ProductVariant','PricingConfig','Inventory','ProductBOM','CapacityConfig','BlockedDate','SubscriptionSchedule','CakeOption','CakeOptionIngredient','CakeAddon','CakeAddonIngredient','SeasonalOccasion'];
const staffTables=['Product','ProductVariant','Category','ProductBOM','Inventory','InventoryMovement','CapacityAllocation','SubscriptionSchedule','BlockedDate','Order','OrderItem','OrderMaterialRequirement','InventoryReservation','Delivery','OrderStatusHistory','SystemNotification','CakeOption','CakeOptionIngredient','CakeAddon','CakeAddonIngredient'];
export async function perform(a:Row|null,action:string,b:Row):Promise<any>{return transaction(async d=>{
if(action==='register')return register(d,b);
if(action==='verify')return verifyCode(d,b);
if(action==='resetRequest'){const account=(await rows(d,'SELECT * FROM "Account" WHERE email=$1',email(b.email)))[0];return account?issueCode(d,account,'password_reset'):{message:'If the account exists, a mock email is available.'}}
if(action==='resendVerification'){const account=await one(d,`SELECT * FROM "Account" WHERE email=$1 AND status='pending_verification'`,email(b.email));return issueCode(d,account,'email_verification')}
assert(a,'Sign in to continue');if(action==='password')return changePassword(d,a,b);requireRole(a,'customer','staff','admin');
if(action==='emailChange')return issueCode(d,a,'email_change',email(b.email));
if(action==='profile'){await update(d,'Account',a.account_id,{first_name:String(b.first_name).trim(),last_name:String(b.last_name).trim(),updated_at:now()});if(a.role==='customer')await update(d,'CustomerProfile',a.customer_id,{mobile_number:String(b.mobile_number??'')});return {message:'Profile updated'}}
if(action==='address'){requireRole(a,'customer');if(b.id)await one(d,'SELECT * FROM "Address" WHERE address_id=$1 AND customer_id=$2',b.id,a.customer_id);assert(b.label&&b.add_line_1&&b.city,'Address label, street, and city required');const v:Row={label:String(b.label),add_line_1:String(b.add_line_1),add_line_2:b.add_line_2||null,city:String(b.city),postal_code:String(b.postal_code??''),landmark:b.landmark||null,latitude:Number(b.latitude),longitude:Number(b.longitude),is_default:!!b.is_default,status:b.status??'active',updated_at:now()};await courierGateway.quote(v);if(v.is_default)await d.$executeRawUnsafe('UPDATE "Address" SET is_default=false WHERE customer_id=$1',a.customer_id);return b.id?update(d,'Address',b.id,v):insert(d,'Address',{...v,customer_id:a.customer_id})}
if(action==='cart'){requireRole(a,'customer');const cart=await one(d,'SELECT * FROM "Cart" WHERE customer_id=$1',a.customer_id);const existing=(await rows(d,'SELECT * FROM "CartItem" WHERE cart_id=$1 AND variant_id=$2',cart.cart_id,b.variant_id))[0];if(Number(b.quantity)===0){if(existing)await d.$executeRawUnsafe('DELETE FROM "CartItem" WHERE cart_item_id=$1',existing.cart_item_id)}else{const q=qty(b.quantity);await one(d,`SELECT * FROM "ProductVariant" WHERE variant_id=$1 AND status='available'`,b.variant_id);if(existing)await update(d,'CartItem',existing.cart_item_id,{quantity:q,updated_at:now()});else await insert(d,'CartItem',{cart_id:cart.cart_id,variant_id:b.variant_id,quantity:q})}const total=await one(d,'SELECT COALESCE(sum(c.quantity*v.final_price),0) AS total FROM "CartItem" c JOIN "ProductVariant" v USING(variant_id) WHERE cart_id=$1',cart.cart_id);await update(d,'Cart',cart.cart_id,{subtotal:num(total.total),updated_at:now()});return {message:'Cart updated'}}
if(action==='checkout'){requireRole(a,'customer');return standardCheckout(d,a,b)}
if(action==='enroll'){requireRole(a,'customer');return enroll(d,a,b)}
if(action==='defer'){requireRole(a,'customer');return defer(d,a,b)}
if(action==='cakeRequest'){requireRole(a,'customer');return cakeRequest(d,a,b)}
if(action==='acceptCake'){requireRole(a,'customer');return acceptCake(d,a,b)}
if(action==='cakeNegotiate'){requireRole(a,'customer');const r=await one(d,'SELECT * FROM "CustomCakeRequest" WHERE custom_request_id=$1 AND customer_id=$2',b.request_id,a.customer_id);assert(!r.accepted_quotation_id,'Accepted request cannot be changed');await d.$executeRawUnsafe(`UPDATE "CustomCakeQuotation" SET status='superseded' WHERE custom_request_id=$1 AND status='issued'`,r.custom_request_id);return update(d,'CustomCakeRequest',r.custom_request_id,{design_description:String(b.design_description),status:'negotiating',updated_at:now()})}
if(action==='quoteCake'){requireRole(a,'admin');return quoteCake(d,a,b)}
if(action==='payment'){requireRole(a,'customer','admin');return paymentOutcome(d,a,b)}
if(action==='retryPayment'){requireRole(a,'customer');return retryPayment(d,a,b)}
if(action==='resolvePayment'){requireRole(a,'admin');return confirmPaid(d,await one(d,`SELECT * FROM "Payment" WHERE order_id=$1 AND status='paid'`,b.order_id),a)}
if(action==='cancelOrder'){requireRole(a,'customer','admin');const o=await one(d,'SELECT * FROM "Order" WHERE order_id=$1 AND (customer_id=$2 OR $3::boolean)',b.order_id,a.customer_id??'',a.role==='admin');assert(o.status==='pending_payment'&&o.type!=='subscription_fulfillment','Only unpaid purchase orders can be cancelled');assert(!(await rows(d,`SELECT 1 FROM "Payment" WHERE order_id=$1 AND status='paid'`,o.order_id)).length,'Paid obligations cannot be cancelled');for(const h of await rows(d,`SELECT * FROM "CheckoutHold" WHERE order_id=$1 AND status='active'`,o.order_id))await releaseHold(d,h,'released');await history(d,o,'cancelled',a);await d.$executeRawUnsafe(`UPDATE "Payment" SET status='cancelled' WHERE order_id=$1 AND status='pending'`,o.order_id);if(o.type==='subscription_purchase'){await d.$executeRawUnsafe(`UPDATE "Order" SET status='cancelled' WHERE order_id IN(SELECT sd.fulfillment_order_id FROM "SubscriptionDelivery" sd JOIN "Subscription" s USING(subscription_id) WHERE s.purchase_order_id=$1)`,o.order_id);await d.$executeRawUnsafe(`UPDATE "SubscriptionDelivery" SET status='cancelled' WHERE subscription_id IN(SELECT subscription_id FROM "Subscription" WHERE purchase_order_id=$1)`,o.order_id);await d.$executeRawUnsafe(`UPDATE "Subscription" SET status='cancelled' WHERE purchase_order_id=$1`,o.order_id)}return {message:'Unpaid order cancelled'}}
if(action==='advance'){requireRole(a,'staff','admin');return advance(d,a,b)}
if(action==='book'){requireRole(a,'admin');return bookDelivery(d,a,b)}
if(action==='track'){requireRole(a,'admin');return trackDelivery(d,a,b)}
if(action==='stock'){requireRole(a,'staff','admin');const inv=await one(d,'SELECT * FROM "Inventory" WHERE inventory_id=$1',b.inventory_id);const change=Number(b.quantity_change);assert(Number.isFinite(change)&&change!==0,'Enter a nonzero stock change');assert(['restock','adjustment'].includes(b.movement_type),'Choose restock or adjustment');assert(b.movement_type!=='restock'||change>0,'Restock must be positive');const reserved=num((await one(d,`SELECT COALESCE(sum(r.quantity),0) AS n FROM "InventoryReservation" r JOIN "OrderMaterialRequirement" m USING(requirement_id) WHERE m.inventory_id=$1 AND r.status IN ('held','confirmed')`,inv.inventory_id)).n);assert(num(inv.stock_on_hand)+change>=reserved,'Adjustment would consume reserved stock; resolve commitments first');const key=String(b.operation_key??crypto.randomUUID());if((await rows(d,'SELECT 1 FROM "InventoryMovement" WHERE operation_key=$1',key)).length)return {message:'Movement already recorded'};const cost=a.role==='admin'&&b.cost_per_unit!==undefined?Number(b.cost_per_unit):num(inv.cost_per_unit);assert(Number.isFinite(cost)&&cost>=0,'Cost must be nonnegative');await insert(d,'InventoryMovement',{inventory_id:inv.inventory_id,performed_by_account_id:a.account_id,movement_type:b.movement_type,quantity_change:change,unit_cost_snapshot:cost,reason:b.movement_type==='adjustment'?(b.reason??'correction'):null,notes:b.notes??'',operation_key:key,occurred_at:now()});await update(d,'Inventory',inv.inventory_id,{stock_on_hand:num(inv.stock_on_hand)+change,cost_per_unit:cost,updated_at:now()});await refreshStock(d);return {message:'Stock movement recorded'}}
if(action==='review'){requireRole(a,'customer');assert(Number.isInteger(Number(b.rating))&&Number(b.rating)>=1&&Number(b.rating)<=5,'Rating must be 1–5');assert((b.images??[]).length<=2,'Maximum two photos');const f=await insert(d,'CustomerFeedback',{customer_id:a.customer_id,order_item_id:b.order_item_id,rating:Number(b.rating),comment:b.comment||null,status:'visible'});for(const url of b.images??[])await insert(d,'FeedbackImage',{feedback_id:f.feedback_id,img_url:url});return f}
if(action==='moderate'){requireRole(a,'admin');return update(d,'CustomerFeedback',b.feedback_id,{status:b.hide?'hidden':'visible',hidden_by_admin_id:b.hide?a.admin_id:null,hidden_reason:b.hide?(b.reason??'other'):null,hidden_at:b.hide?now():null,updated_at:now()})}
if(action==='ack'){requireRole(a,'staff','admin');const n=await one(d,'SELECT * FROM "SystemNotification" WHERE system_notification_id=$1',b.id);assert(n.recipient_role==='all'||n.recipient_role===a.role,'Notification is restricted');return update(d,'SystemNotification',b.id,{is_read:true,read_at:now()})}
if(action==='draft'){requireRole(a,'admin');const p=await one(d,'SELECT * FROM "PostDraft" WHERE draft_id=$1',b.id);if(b.regenerate){const product=p.product_id?await one(d,'SELECT * FROM "Product" WHERE product_id=$1',p.product_id):null;const output=await marketingGateway.generate({name:product?.name??'Kitchen406 seasonal offerings',availability:'Check current availability before ordering.'});return update(d,'PostDraft',b.id,{caption:output.caption,img_url:output.image,regenerate_count:p.regenerate_count+1,status:'pending_review',updated_at:now()})}assert(['pending_review','approved','rejected'].includes(b.status),'Invalid review status');return update(d,'PostDraft',b.id,{caption:String(b.caption??p.caption),status:b.status,was_edited:p.was_edited||b.caption!==p.caption,reviewed_by_admin_id:a.admin_id,reviewed_at:now(),updated_at:now()})}
if(action==='staffCreate'){requireRole(a,'admin');const account=await insert(d,'Account',{email:email(b.email),password_hash:await bcrypt.hash(password(b.password),12),first_name:String(b.first_name),last_name:String(b.last_name),role:'staff',status:'active',email_verified_at:now()});await insert(d,'StaffProfile',{account_id:account.account_id,created_by_admin_id:a.admin_id,is_temp_pass_changed:false});await notify(d,account.account_id,'account_setup','account_verification',account.account_id,'Your staff account is ready. Use the temporary password supplied by your owner, then change it.','setup:'+account.account_id);return {message:'Staff account created; password change required'}}
if(action==='accountStatus'){requireRole(a,'admin');assert(b.id!==a.account_id,'Cannot deactivate your own account');assert(['active','inactive','suspended'].includes(b.status),'Invalid account status');const target=await one(d,'SELECT * FROM "Account" WHERE account_id=$1',b.id);assert(target.role!=='admin','Owner accounts cannot be disabled in this prototype');return update(d,'Account',b.id,{status:b.status,updated_at:now()}).then(()=>({message:'Account status updated'}))}
if(action==='save'){requireRole(a,'admin');assert(editable.includes(b.entity),'Entity is not directly editable');const table=b.entity as string;const value:Row={};for(const [k,v] of Object.entries(b.values??{})){assert(meta[table].columns[k]&&!meta[table].columns[k].primary,'Unknown or protected field');if(['created_at','updated_at','created_by_admin_id','updated_by_admin_id','stock_on_hand','suggested_price'].includes(k))continue;const col=meta[table].columns[k];value[k]=v===''&&col.nullable?null:col.type==='integer'||col.type.startsWith('numeric')?Number(v):col.type==='boolean'?!!v:col.type==='date'||col.type==='timestamptz'?new Date(String(v)):v}if(meta[table].columns.created_by_admin_id&&!b.id)value.created_by_admin_id=a.admin_id;if(meta[table].columns.updated_by_admin_id)value.updated_by_admin_id=a.admin_id;if(meta[table].columns.updated_at)value.updated_at=now();if(table==='Inventory'){delete value.status;if(!b.id)value.stock_on_hand=0}if(table==='CapacityConfig'||table==='BlockedDate'||table==='SubscriptionSchedule'){const commitments=await rows(d,`SELECT 1 FROM "CapacityAllocation" WHERE status IN ('held','confirmed') LIMIT 1`);assert(!commitments.length,'Scheduling changes are locked while commitments exist; inspect allocations before changing these settings')}const result=b.id?await update(d,table,b.id,value):await insert(d,table,value);await refreshStock(d);return result}
if(action==='reprice'){requireRole(a,'admin');const config=await one(d,'SELECT * FROM "PricingConfig"');for(const v of await rows(d,'SELECT * FROM "ProductVariant"')){const r=await one(d,'SELECT COALESCE(sum(b.quantity_required*i.cost_per_unit),0) AS cost FROM "ProductBOM" b JOIN "Inventory" i USING(inventory_id) WHERE b.variant_id=$1',v.variant_id);await update(d,'ProductVariant',v.variant_id,{suggested_price:money((num(r.cost)+num(v.utility_overhead??config.default_utility_overhead))*(1+num(config.markup_percentage)/100)),updated_at:now()})}return {message:'Suggested prices recalculated; selling prices unchanged'}}
if(action==='jobs'){requireRole(a,'admin');return jobs(d,true)}
if(action==='settings'){requireRole(a,'admin');const hours=Number(b.offsetHours??settings().offsetHours);assert(Number.isFinite(hours)&&hours>=0&&hours<=24*365,'Clock offset must be 0–8760 hours');configure({offsetHours:hours,notificationFailure:!!b.notificationFailure,aiFailure:!!b.aiFailure});return {message:'Prototype controls updated',settings:settings()}}
throw new Error('Unknown action');})}
