import {rows,one,insert,update,num,money,type DB,type Row} from './db';import {now,date,addDays,week,businessDate,fulfillmentTime,writeOutbox} from './runtime';import {courierGateway,paymentGateway} from './integrations';
export function assert(ok:any,message:string):asserts ok{if(!ok)throw new Error(message)}
export function qty(v:any){const n=Number(v);assert(Number.isInteger(n)&&n>0&&n<=10000,'Quantity must be a positive integer');return n}
export function validDate(v:any){assert(typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&!isNaN(new Date(v).getTime()),'Valid date required');return v}
export async function notice(d:DB,role:string,type:string,entity:string,id:string,message:string){return insert(d,'SystemNotification',{recipient_role:role,notification_type:type,related_entity_type:entity,related_entity_id:id,message,created_at:now()})}
export async function notify(d:DB,account:string,type:string,entity:string,id:string,message:string,key:string,sms=false){for(const provider of sms?['brevo','semaphore']:['brevo']){const event=key+':'+provider;if((await rows(d,'SELECT 1 FROM "NotificationLog" WHERE event_key=$1',event)).length)continue;const n=await insert(d,'NotificationLog',{recipient_account_id:account,type,provider,status:'pending',related_entity_type:entity,related_entity_id:id,event_key:event,created_at:now()});writeOutbox(n.notification_log_id,{message,provider,account_id:account,created_at:now()})}}
export async function history(d:DB,o:Row,status:string,a?:Row){await update(d,'Order',o.order_id,{status,updated_at:now()});await insert(d,'OrderStatusHistory',{order_id:o.order_id,status,changed_by_account_id:a?.account_id??null,changed_at:now()})}
export async function refreshStock(d:DB){await d.$executeRawUnsafe(`UPDATE "Inventory" i SET status=CASE WHEN i.stock_on_hand-COALESCE((SELECT sum(r.quantity) FROM "InventoryReservation" r JOIN "OrderMaterialRequirement" m USING(requirement_id) WHERE m.inventory_id=i.inventory_id AND r.status IN ('held','confirmed')),0)<=0 THEN 'unavailable' WHEN i.stock_on_hand-COALESCE((SELECT sum(r.quantity) FROM "InventoryReservation" r JOIN "OrderMaterialRequirement" m USING(requirement_id) WHERE m.inventory_id=i.inventory_id AND r.status IN ('held','confirmed')),0)<=i.reorder_threshold THEN 'low_stock' ELSE 'available' END, updated_at=now()`)}
export async function available(d:DB,id:string){const i=await one(d,`SELECT i.*,i.stock_on_hand-COALESCE((SELECT sum(r.quantity) FROM "InventoryReservation" r JOIN "OrderMaterialRequirement" m USING(requirement_id) WHERE m.inventory_id=i.inventory_id AND r.status IN ('held','confirmed')),0) AS available FROM "Inventory" i WHERE inventory_id=$1`,id);return num(i.available)}
export async function materials(d:DB,variantId:string,quantity:number){const list=await rows(d,'SELECT b.inventory_id,b.quantity_required,i.cost_per_unit FROM "ProductBOM" b JOIN "Inventory" i USING(inventory_id) WHERE variant_id=$1',variantId);assert(list.length,'Product recipe is missing');return list.map(x=>({inventory_id:x.inventory_id,quantity_required:num(x.quantity_required)*quantity,cost_per_unit:num(x.cost_per_unit)}))}
export async function requirements(d:DB,orderId:string,items:Row[],day:string,subscription:boolean){const aggregate=new Map<string,number>();for(const i of items)aggregate.set(i.inventory_id,(aggregate.get(i.inventory_id)??0)+num(i.quantity_required));for(const [inventory_id,q] of aggregate){await insert(d,'OrderMaterialRequirement',{order_id:orderId,inventory_id,quantity_required:q,fulfillment_date:new Date(day),reserve_at:subscription?new Date(fulfillmentTime(day).getTime()-48*3600000):now()})}}
export async function reserveMaterials(d:DB,orderId:string,hold:Row|null,status='held',force=false){const reqs=await rows(d,'SELECT * FROM "OrderMaterialRequirement" WHERE order_id=$1',orderId);for(const m of reqs){if(!force&&new Date(m.reserve_at)>now())continue;const existing=await rows(d,`SELECT * FROM "InventoryReservation" WHERE requirement_id=$1 AND status IN ('held','confirmed','consumed')`,m.requirement_id);if(existing.length)continue;assert(await available(d,m.inventory_id)>=num(m.quantity_required),'Insufficient ingredient stock for this fulfillment');await insert(d,'InventoryReservation',{requirement_id:m.requirement_id,hold_id:hold?.hold_id??null,quantity:num(m.quantity_required),status,expires_at:status==='held'?hold?.expires_at:null})}await refreshStock(d)}
export async function validateDay(d:DB,kind:string,day:string,checkLead=true){validDate(day);const c=await one(d,'SELECT * FROM "CapacityConfig" WHERE order_type=$1',kind);assert(day>businessDate(),'Same-day fulfillment is not supported');if(checkLead){const hours=num(c.lead_time_value)*(c.lead_time_unit==='days'?24:1);const deadline=new Date(fulfillmentTime(day).getTime()-hours*3600000);const cutoffDay=new Date(deadline.getTime()+8*3600000).toISOString().slice(0,10);const cutoff=new Date(cutoffDay+'T'+c.cutoff_time+':00+08:00');assert(now()<=deadline&&now()<=cutoff,'Minimum lead time or booking cutoff has passed')}assert(!(await rows(d,'SELECT 1 FROM "BlockedDate" WHERE date=$1::date',day)).length,'This date is blocked');return c}
export async function allocate(d:DB,kind:string,day:string,product:string|null,quantity:number,source:string,fulfillment:string|null,hold:Row|null,cycle:number|null,status='held',checkLead=true){const c=await validateDay(d,kind,day,checkLead);const from=kind==='standard'?day:week(day);const to=kind==='standard'?day:addDays(from,6);const used=await rows(d,`SELECT * FROM "CapacityAllocation" WHERE capacity_config_id=$1 AND fulfillment_date BETWEEN $2::date AND $3::date AND status IN ('held','confirmed','fulfilled')`,c.capacity_config_id,from,to);if(kind==='custom_cake'){assert(used.reduce((s,x)=>s+num(x.quantity),0)+quantity<=num(c.max_cakes_per_week),'Weekly cake capacity is full');assert(used.filter(x=>date(x.fulfillment_date)===day).reduce((s,x)=>s+num(x.quantity),0)+quantity<=num(c.max_cakes_per_day),'Daily cake capacity is full')}else{assert(used.filter(x=>x.product_id===product).reduce((s,x)=>s+num(x.quantity),0)+quantity<=num(c.max_units),'Product capacity is full');if(kind==='standard'){const varieties=new Set(used.map(x=>x.product_id));varieties.add(product);assert(varieties.size<=num(c.max_varieties_per_day),'Daily product variety limit reached')}}return insert(d,'CapacityAllocation',{capacity_config_id:c.capacity_config_id,product_id:product,source_order_id:source,fulfillment_order_id:fulfillment,hold_id:hold?.hold_id??null,cycle_number:cycle,fulfillment_date:new Date(day),quantity,status,expires_at:status==='held'?hold?.expires_at:null})}
export async function checkoutAddress(d:DB,a:Row,id:string|undefined,method:string){assert(['pickup','delivery'].includes(method),'Choose pickup or delivery');if(method==='pickup')return {address_id:null,address_snapshot:null,fee:0};const address=await one(d,`SELECT * FROM "Address" WHERE address_id=$1 AND customer_id=$2 AND status='active'`,id??'',a.customer_id);const quote=await courierGateway.quote(address);return {address_id:address.address_id,address_snapshot:address,fee:quote.fee}}
export async function newOrder(d:DB,a:Row,type:string,day:string|null,method:string|null,address:Row,total=0,payable=0){return insert(d,'Order',{customer_id:a.customer_id,type,fulfillment_date:day?new Date(day):null,fulfillment_method:method,address_id:address.address_id??null,address_snapshot:address.address_snapshot??null,checkout_delivery_fee:address.fee??0,total,amount_payable:payable,ref_number:'K406-'+crypto.randomUUID().slice(0,8).toUpperCase(),status:'pending_payment',placed_at:now()})}
export async function newHold(d:DB,o:Row){return insert(d,'CheckoutHold',{order_id:o.order_id,created_at:now(),expires_at:new Date(now().getTime()+15*60000),status:'active'})}
export async function newPayment(d:DB,o:Row,h:Row){const p=await paymentGateway.create(num(o.amount_payable));return insert(d,'Payment',{order_id:o.order_id,hold_id:h.hold_id,paymongo_id:p.id,amount:num(o.amount_payable),qr_img_url:p.qr,status:'pending',created_at:now(),expires_at:h.expires_at})}
export async function releaseHold(d:DB,h:Row,status='expired'){await update(d,'CheckoutHold',h.hold_id,{status,released_at:now()});await d.$executeRawUnsafe(`UPDATE "CapacityAllocation" SET status=$2,released_at=$3 WHERE hold_id=$1 AND status='held'`,h.hold_id,status==='expired'?'expired':'released',now());await d.$executeRawUnsafe(`UPDATE "InventoryReservation" SET status=$2,released_at=$3 WHERE hold_id=$1 AND status='held'`,h.hold_id,status==='expired'?'expired':'released',now());await refreshStock(d)}
export async function expire(d:DB){for(const h of await rows(d,`SELECT * FROM "CheckoutHold" WHERE status='active' AND expires_at<=$1`,now())){await releaseHold(d,h);await d.$executeRawUnsafe(`UPDATE "Payment" SET status='expired' WHERE hold_id=$1 AND status='pending'`,h.hold_id)}await d.$executeRawUnsafe(`UPDATE "CustomCakeQuotation" SET status='expired' WHERE status='issued' AND expires_at<=$1`,now())}
export async function item(d:DB,orderId:string,variant:Row,q:number,price?:number){const recipe=await materials(d,variant.variant_id,1);const pricing=await one(d,'SELECT * FROM "PricingConfig" LIMIT 1');return insert(d,'OrderItem',{order_id:orderId,variant_id:variant.variant_id,quotation_id:null,quantity:q,unit_price_snapshot:price??num(variant.final_price),material_cost_snapshot:recipe.reduce((s,x)=>s+x.quantity_required*x.cost_per_unit,0),overhead_cost_snapshot:num(variant.utility_overhead??pricing.default_utility_overhead)})}
export async function completeSubscription(d:DB,orderId:string){const sd=(await rows(d,'SELECT * FROM "SubscriptionDelivery" WHERE fulfillment_order_id=$1',orderId))[0];if(!sd)return;await update(d,'SubscriptionDelivery',sd.subscription_delivery_id,{status:'fulfilled',fulfilled_at:now()});const pending=await rows(d,`SELECT 1 FROM "SubscriptionDelivery" WHERE subscription_id=$1 AND status<>'fulfilled'`,sd.subscription_id);if(!pending.length){const sub=await update(d,'Subscription',sd.subscription_id,{status:'completed',updated_at:now()});const customer=await one(d,'SELECT * FROM "CustomerProfile" WHERE customer_id=$1',sub.customer_id);await notify(d,customer.account_id,'subscription_renewal_reminder','subscription',sub.subscription_id,'Your four deliveries are complete. Re-enroll to begin another prepaid cycle.','renew:'+sub.subscription_id)}}
