const fs=require('node:fs');
(async()=>{
const targets=await (await fetch('http://127.0.0.1:9222/json')).json();
const ws=new WebSocket(targets.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise(r=>ws.onopen=r);
let seq=0;const pending=new Map(),errors=[];ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){pending.get(m.id)?.(m);pending.delete(m.id);}else if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.text+': '+m.params.exceptionDetails.exception?.description);};
const send=(method,params={})=>new Promise((r,j)=>{const id=++seq;pending.set(id,r);ws.send(JSON.stringify({id,method,params}));setTimeout(()=>{if(pending.has(id)){pending.delete(id);j(Error('CDP timeout: '+method));}},15000).unref();});
const evaluate=async(expression)=>{const r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.result.exceptionDetails)throw Error(r.result.exceptionDetails.exception?.description);return r.result.result.value;};
const wait=(ms=120)=>new Promise(r=>setTimeout(r,ms));
const go=async route=>{await evaluate('location.hash='+JSON.stringify('#/'+route));await wait();};
let checks=0;const assert=async(expr,name)=>{if(!await evaluate(expr))throw Error('FAIL: '+name);console.log('PASS '+name);checks++;};
await send('Runtime.enable');await send('Page.enable');
await send('Page.navigate',{url:require('node:url').pathToFileURL(require('node:path').resolve(__dirname,'../index.html')).href});
await wait(3000);
await assert("document.querySelectorAll('#product-grid article').length===8",'catalog initial page');
await evaluate("document.getElementById('product-search-input').value='babka';document.getElementById('product-search-input').dispatchEvent(new Event('input'))");
await assert("document.querySelectorAll('#product-grid article').length===1",'catalog search');
await evaluate("K406.catalog.reset();document.getElementById('next-page-btn').click();document.getElementById('next-page-btn').click()");
await assert("document.querySelectorAll('#product-grid article').length===4&&document.getElementById('next-page-btn').disabled",'catalog last page');
await evaluate("K406.catalog.setState('error')");
await assert("!document.getElementById('catalog-error').classList.contains('hidden')",'catalog error');
await evaluate("K406.catalog.reset()");
await go('product/1');
await assert("document.querySelector('#mainProductContent h1').textContent==='Braided Chocolate Babka'",'Babka detail');
await evaluate("selectVariant('large');adjustQty(1)");
await assert("document.getElementById('subtotalDisplay').textContent.includes('960')",'variant and quantity subtotal');
await evaluate("setAvailability(false)");
await assert("document.getElementById('addToCartBtn').disabled",'sold-out action disabled');
await evaluate("setAvailability(true);handleAddToCart()");await wait();
await assert("location.hash==='#/sign-in'&&K406.modal==='auth-modal'",'protected sign in');
await evaluate("K406.authUI.fill();document.getElementById('auth-form').requestSubmit()");await wait(850);
await assert("K406.auth==='signedin'&&location.hash==='#/product/1'&&document.getElementById('subtotalDisplay').textContent.includes('960')",'sign-in returns with selection preserved');
await evaluate("setEligibility('eligible');openReviewModal();setModalStarRating(5);toggleMockPhoto(1);K406.product.state.error=true;handleReviewSubmit()");await wait(750);
await assert("!document.getElementById('modalSubmitError').classList.contains('hidden')",'review submission error');
await evaluate("K406.product.state.error=false;handleReviewSubmit()");await wait(750);
await assert("K406.product.state.submitted.has(1)&&!document.getElementById('modalSubmitSuccess').classList.contains('hidden')",'review submission success');
await evaluate("closeReviewModal()");
await go('product/2');
await assert("document.querySelector('#mainProductContent h1').textContent==='Country Sourdough Batard'&&document.getElementById('variantSection').classList.contains('hidden')&&document.getElementById('review-summary').hidden",'other product data isolated');
await go('product/999');
await assert("!document.getElementById('pageNotFoundState').classList.contains('hidden')",'unknown product');
await go('shop');await go('register');
await evaluate("document.getElementById('auth-form').requestSubmit()");
await assert("document.querySelectorAll('#auth-form [aria-invalid=true]').length>=5",'registration validation');
await evaluate("K406.setAuth('guest');K406.authUI.fill();document.getElementById('auth-form').requestSubmit()");await wait(850);
await assert("location.hash==='#/verify'&&document.querySelectorAll('[data-digit]').length===6",'registration verification handoff');
await evaluate("K406.authUI.simulate('incorrect');K406.authUI.state.attempts=4;document.getElementById('auth-form').requestSubmit()");await wait(800);
await assert("K406.authUI.state.mode==='max_attempts'&&document.getElementById('verify-submit').disabled",'OTP attempt limit');
await evaluate("document.querySelector('[data-auth-action=resend]').click()");await wait(800);
await assert("K406.authUI.state.attempts===0&&K406.authUI.state.mode==='resend_sent'",'OTP resend resets attempts');
await evaluate("K406.authUI.fill();document.getElementById('auth-form').requestSubmit()");await wait(800);
await assert("K406.authUI.state.mode==='success'&&K406.auth==='guest'",'verification does not sign in');
await go('sign-in');await go('forgot');
await evaluate("K406.authUI.fill();document.getElementById('auth-form').requestSubmit()");await wait(800);
await assert("K406.authUI.state.mode==='success'",'forgot password confirmation');
await evaluate("document.querySelector('[data-auth-action=reset-link]').click()");await wait();
await assert("location.hash==='#/reset'&&document.getElementById('auth-password')",'demo reset link');
await evaluate("K406.authUI.fill();document.getElementById('auth-form').requestSubmit()");await wait(800);
await assert("K406.authUI.state.mode==='success'&&!K406.authUI.state.resetValid",'reset password confirmation');
await go('forgot');await go('reset');
await assert("K406.authUI.state.mode==='invalid'",'used or absent reset link invalid');
await evaluate("K406.authUI.simulate('expired')");
await assert("document.getElementById('auth-card-content').textContent.includes('expired')",'expired link preview');
await go('shop');
for(const width of [1440,768,390,320]){
 await send('Emulation.setDeviceMetricsOverride',{width,height:900,deviceScaleFactor:1,mobile:false});
 await wait();
 await assert("document.documentElement.scrollWidth<=innerWidth",'catalog fits '+width);
 await go('product/1');
 await assert("document.documentElement.scrollWidth<=innerWidth",'product fits '+width);
 await go('register');
 await assert("document.documentElement.scrollWidth<=innerWidth&&document.querySelector('.dialog-card').getBoundingClientRect().width<=innerWidth",'auth fits '+width);
 if(width===390){const shot=await send('Page.captureScreenshot',{format:'png'});fs.mkdirSync('verification',{recursive:true});fs.writeFileSync('verification/mobile-registration.png',Buffer.from(shot.result.data,'base64'));}
 await go('shop');
}
await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});
await wait(300);
const shot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});fs.mkdirSync('verification',{recursive:true});fs.writeFileSync('verification/desktop-catalog.png',Buffer.from(shot.result.data,'base64'));
await go('product/1');
const detail=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});fs.writeFileSync('verification/desktop-product.png',Buffer.from(detail.result.data,'base64'));
if(errors.length)throw Error(errors.join('\n'));
console.log('COMPLETE '+checks+' checks; no uncaught browser exceptions.');ws.close();
})().catch(e=>{console.error(e);process.exit(1)});
