const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{
 const targets=await(await fetch('http://127.0.0.1:9222/json')).json();const ws=new WebSocket(targets.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise(r=>ws.onopen=r);let seq=0;const pending=new Map(),errors=[];
 ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){pending.get(m.id)?.(m);pending.delete(m.id);}else if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.exception?.description||m.params.exceptionDetails.text);};
 const send=(method,params={})=>new Promise(r=>{const id=++seq;pending.set(id,r);ws.send(JSON.stringify({id,method,params}));});
 const run=async expression=>{const m=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(m.result?.exceptionDetails)throw Error(m.result.exceptionDetails.exception?.description);return m.result.result.value;};
 const wait=()=>new Promise(r=>setTimeout(r,180));const go=async route=>{await run(`location.hash=${JSON.stringify('#/'+route)}`);await wait();};let checks=0;const check=async(expr,label)=>{assert(await run(expr.includes("await ")?"(async()=> ("+expr+"))()":expr),label);console.log('PASS',label);checks++;};
 await send('Runtime.enable');await send('Page.enable');errors.length=0;await send('Page.navigate',{url:require('node:url').pathToFileURL(path.resolve('index.html')).href});await new Promise(r=>setTimeout(r,1800));
 await run('window.A=K406;window.S=A.staff;window.I=A.inventory;window.C=A.commerce');
 await check('!!A.$("account-menu") && !!document.querySelector("header")','shared shell initializes');
 await go('staff');await check('A.$("staff-view").textContent.includes("Staff access required")','guest denied');
 await run('S.enter()');await wait();await run('S.seed()');
 await check('S.list().length===4','coherent staff fixture');
 await check('S.list().every(o=>!["total","price","address","customer_id","email","phone"].some(k=>Object.hasOwn(o,k)))','safe projection');
 await run('S.account.status="inactive"');await check('S.list().length===0 && S.transition("STAFF-DEMO-1","preparing",0,"blocked").includes("access")','inactive staff denied');await run('S.account.status="active";S.account.setup=false');await check('!S.allowed()','incomplete setup denied');await run('S.account.setup=true');
 await check('I.recipe(999)===null && I.recipe(20).flour===undefined && I.recipe(20).butter===198','explicit product recipes fail closed');
 for(const route of ['staff','staff/production','staff/production/STAFF-DEMO-1','staff/inventory','staff/movements','staff/recipes','staff/calendar','staff/notifications','staff/settings']){await go(route);await check('!!A.$("staff-view").querySelector("h1")','render '+route);}
 await run('window.before=I.item("flour").stock;window.available=I.available("flour");window.need=I.plan(S.orders().find(o=>o.id==="STAFF-DEMO-1")).flour');
 await check('S.transition("STAFF-DEMO-1","preparing",0,"test-start")===""','start preparation');
 await check('I.item("flour").stock===before-need && I.available("flour")===available','reservation consumed without double subtraction');
 await check('S.transition("STAFF-DEMO-1","preparing",0,"test-start")==="" && I.item("flour").stock===before-need','repeat safe');
 await check('S.transition("STAFF-DEMO-1","ready",0,"stale")!==""','stale update rejected');
 await check('S.transition("STAFF-DEMO-1","ready",1,"ready")===""','mark ready');
 await check('S.transition("STAFF-DEMO-1","completed",2,"complete")==="" && I.item("flour").stock===before-need','complete pickup without deduction');
 await check('S.transition("STAFF-DEMO-2","completed",0,"bad")!==""','delivery cannot complete as pickup');
 await run('window.butter=I.item("butter").stock;I.item("butter").stock=0;window.flour=I.item("flour").stock');
 await check('S.transition("STAFF-DEMO-2","preparing",0,"shortage")!=="" && I.item("flour").stock===flour','shortage atomic rollback');
 await run('I.item("butter").stock=butter');
 await check('I.change({id:"butter",quantity:0,type:"adjustment",reason:"miscount",key:"zero"})==="" && I.item("butter").stock===0','physical count accepts zero');
 await check('I.change({id:"butter",quantity:1000,type:"restock",key:"restock"})==="" && I.item("butter").stock===1000','restock');
 await check('I.change({id:"butter",quantity:1000,type:"restock",key:"restock"})==="" && I.item("butter").stock===1000','restock idempotent');
 await go('staff/production/STAFF-DEMO-3');await run('document.querySelector("#staff-view [data-staff=transition]").click()');await check('A.modal==="staff-modal"','transition dialog');await run('document.querySelector("[data-staff=confirm-transition]").click()');await check('S.list().find(o=>o.id==="STAFF-DEMO-3").status==="preparing" && A.modal===null','dialog updates same order');
 await go('staff/calendar');await run('S.calendarDate=A.schedule.add(A.schedule.today(),2);S.render()');await check('A.$("staff-view").textContent.includes("STAFF-DEMO-3")','calendar selected agenda');
 await go('staff/notifications');await run('document.querySelector("[data-staff=read-all]").click()');await check('S.events.every(e=>e.read)','shared acknowledgement');
 await check('(await S.password("wrong","Newpass123","Newpass123")).includes("Incorrect")','reject wrong password');
 await check('(await S.password("Kitchen406!","Newpass123","Newpass123"))===""','password update');
 await check('(await S.password("Kitchen406!","Otherpass123","Otherpass123")).includes("Incorrect")','old password rejected');
 for(const width of [1440,768,390,320]){await send('Emulation.setDeviceMetricsOverride',{width,height:1000,deviceScaleFactor:1,mobile:false});for(const route of ['staff','staff/inventory','staff/calendar','staff/settings']){await go(route);await check('document.documentElement.scrollWidth<=innerWidth+1',route+' fits '+width);}}
 await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});await go('staff');const shot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});fs.writeFileSync('verification/staff-dashboard-desktop.png',Buffer.from(shot.result.data,'base64'));
 await run('S.leave()');await wait();await check('A.account.allowed() && A.$("catalog-view").hidden===false','customer restored');
 
 await run('C.sampleCart();Object.assign(C.state.draft,{method:"pickup",date:"2026-10-24"});window.customerOrder=C.createOrder();C.setPayment(customerOrder,"confirmed");window.customerStock=I.item("flour").stock');
 await check('customerOrder.paid && I.reservations.get(customerOrder.id).status==="confirmed"','customer purchase reserves materials');
 await run('A.cakes.sampleDraft();window.request=A.cakes.submit();window.quote=A.cakes.issue(request);window.cakeOrder=A.cakes.accept(quote);A.cakes.pay(cakeOrder,"confirmed")');
 await check('cakeOrder.paid && cakeOrder.status==="confirmed"','cake quotation payment shares inventory');
 await run('window.purchase={id:"TEST-SUB-PAY",paid:false,payment:"waiting",attempts:[],snapshot:{productId:1,variantId:"standard",quantity:1,dates:["2026-10-23","2026-10-30","2026-11-06","2026-11-13"],address:{},fee:100,unit:340},created:Date.now()};window.subscription=A.subscriptions.pay(purchase,"confirmed")');
 await check('subscription.deliveries.length===4','subscription creates four fulfillments');
 await run('S.enter()');await wait();
 await check('S.transition(customerOrder.id,"preparing",0,"customer-prep")===""','staff prepares customer purchase');
 await check('S.transition(cakeOrder.id,"preparing",0,"cake-prep")==="" && cakeOrder.type==="cake"','cake identity preserved during consumption');
 await check('A.cakes.holds.find(h=>h.orderId===cakeOrder.id).status==="confirmed"','cake capacity retained after material consumption');
 await check('S.transition(subscription.deliveries[0].orderId,"preparing",0,"subscription-prep")==="" && subscription.deliveries[0].status==="preparing"','weekly delivery lifecycle synchronized');
 await check('S.transition(customerOrder.id,"ready",1,"customer-ready")==="" && S.transition(customerOrder.id,"completed",2,"customer-done")===""','staff completes original customer pickup');
 await go('staff/production/'+await run('cakeOrder.id'));await check('A.$("staff-view").textContent.includes("Owner delivery") && !A.$("staff-view").textContent.includes("climate-controlled")','cake detail uses owner delivery');
 await run('S.leave()');await wait();await go('orders/'+await run('customerOrder.id'));
 await check('A.$("commerce-view").textContent.toLowerCase().includes("completed")','customer sees staff completion');
 await check('A.notifications.events.some(e=>e.customer_id===customerOrder.customer_id && e.path==="orders/"+customerOrder.id && e.message.includes("completed"))','notification targets original customer');
 await run('A.setAuth("guest")');await go('sign-in');await run('document.querySelector("#auth-email").value=S.account.email;document.querySelector("#auth-password").value="Newpass123";document.querySelector("#auth-form").requestSubmit()');await new Promise(r=>setTimeout(r,1100));
 await check('S.allowed() && A.route==="staff"','provisioned staff sign-in uses changed password');
 console.log('ERRORS',errors);assert.equal(errors.length,0);console.log('COMPLETE',checks,'Phase 5 browser checks');ws.close();
})().catch(e=>{console.error(e);process.exit(1)});
