const fs=require('node:fs'),path=require('node:path');
(async()=>{
 const targets=await(await fetch('http://127.0.0.1:9222/json')).json(),ws=new WebSocket(targets.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise(r=>ws.onopen=r);
 let serial=0,checks=0;const pending=new Map(),errors=[];
 ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){pending.get(m.id)?.(m);pending.delete(m.id);}else if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.exception?.description||m.params.exceptionDetails.text);};
 const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++serial;pending.set(id,resolve);ws.send(JSON.stringify({id,method,params}));setTimeout(()=>{if(pending.delete(id))reject(Error('Timeout '+method));},15000).unref();});
 const run=async expression=>{const m=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(m.result.exceptionDetails)throw Error(m.result.exceptionDetails.exception?.description);return m.result.result.value;};
 const wait=(ms=180)=>new Promise(r=>setTimeout(r,ms));
 const go=async route=>{await run('(()=>{const target='+JSON.stringify('#/'+route)+';if(location.hash===target)window.dispatchEvent(new HashChangeEvent("hashchange"));else location.hash=target;})()');await wait();};
 const click=async selector=>{await run(`document.querySelector(${JSON.stringify(selector)}).click()`);await wait();};
 const action=name=>click('[data-p4="'+name+'"]');
 const assert=async(expr,label)=>{if(!await run(expr))throw Error('FAIL '+label);checks++;console.log('PASS '+label);};
 const fill=async(selector,value)=>run(`(()=>{const e=document.querySelector(${JSON.stringify(selector)});e.value=${JSON.stringify(value)};e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}));})()`);
 const upload=async(slot,file='assets/custom-cake.png')=>{const doc=await send('DOM.getDocument'),node=await send('DOM.querySelector',{nodeId:doc.result.root.nodeId,selector:'#cake-file-'+slot});await send('DOM.setFileInputFiles',{nodeId:node.result.nodeId,files:[path.resolve(file)]});await wait(450);};
 await send('Runtime.enable');await send('Page.enable');await send('Page.navigate',{url:require('node:url').pathToFileURL(path.resolve('index.html')).href});await wait(2200);
 await run('window.A=K406;window.K=A.cakes;window.C=A.commerce;window.P=A.account;C.addressMap.mount=()=>{}');
 await go('custom-cakes');await assert('!!document.querySelector(".cake-hero")','public cake introduction');await action('cake-start');await assert('document.getElementById("phase4-view").textContent.includes("Sign in to continue")','builder account gate');
 await click('#phase4-view a[href="#/sign-in"]');await run('A.authUI.fill();document.getElementById("auth-form").requestSubmit()');await wait(1000);
 await assert('A.auth==="signedin"&&location.hash==="#/custom-cakes/request/details"','sign-in resumes request');
 await click('#account-menu-toggle');await assert('!document.getElementById("account-menu").hidden&&A.auth==="signedin"','account menu no longer signs out');await click('#account-menu-toggle');
 await click('[data-p4=cake-date][data-value="2026-10-24"]');await fill('#cake-window','morning');await action('cake-next');
 await assert('K.selected().length===0&&K.estimate().total===0&&document.querySelector("[data-p4=cake-next]").disabled','options start unselected with zero estimate');
 for(const id of ['round','chocolate','eight','cream','buttercream'])await click('[data-p4=cake-option][data-id="'+id+'"]');
 await click('[data-p4=cake-addon][data-delta="1"]');await click('[data-p4=cake-addon][data-delta="1"]');await assert('K.estimate().total===130000','selected estimate is 1300');await action('cake-next');
 await assert('document.querySelector("[data-p4=cake-next]").disabled','reference required');
 await run(`(()=>{const file=new File(['invalid'],'bad.txt',{type:'text/plain'}),d=new DataTransfer();d.items.add(file);const e=document.getElementById('cake-file-0');e.files=d.files;e.dispatchEvent(new Event('change',{bubbles:true}));})()`);await wait();
 await assert('K.builder.uploadError.includes("10 MB")&&!K.state.draft.images[0]','invalid image type rejected');
 for(let slot=0;slot<3;slot++)await upload(slot);
 await assert('K.state.draft.images.filter(i=>i?.status==="ready").length===3','three actual local images validated');
 await action('cake-enlarge');await assert('A.modal==="phase4-modal"&&document.getElementById("app-shell").inert','reference preview dialog locks background');await action('close');
 await fill('#cake-notes','Soft cream and sage, with Happy Birthday lettering.');await action('cake-next');
 await assert('document.querySelectorAll("#phase4-view .cake-image-button").length===3','review retains all references');
 await run('K.mock.submit="error"');await action('cake-submit');await wait(450);await assert('K.state.requests.length===0&&K.message.includes("could not")','failed submission preserves draft');
 await run('K.mock.submit="normal"');await action('cake-submit');await wait(450);
 await assert('K.state.requests.length===1&&K.holds.length===0&&location.hash.startsWith("#/cake-requests/")','submission creates request without hold');
 await run('window.r=K.state.requests[0]');await assert('r.status==="pending_review"&&r.snapshot.images.filter(Boolean).length===3','request detail awaiting review with references');
 await action('qa-quote-issue');await run('window.v1=K.versions(r)[0]');await assert('v1.total===200000&&document.getElementById("phase4-view").textContent.includes("2,000")','owner fixture issues first quotation');
 await action('qa-quote-revise');await run('window.q=K.versions(r)[0]');await assert('q.total===220000&&v1.status==="superseded"','revised quotation preserves prior version');
 await go(await run('K.quotePath(v1)'));await assert('!document.querySelector("[data-p4=quote-accept]")&&document.getElementById("phase4-view").textContent.includes("2,000")','historical quotation has own price and no acceptance');
 await go(await run('K.quotePath(q)'));await action('quote-decline');await fill('#quote-reason','Please keep the soft cream palette.');await run('document.getElementById("quote-decline-form").requestSubmit()');await wait();
 await assert('q.status==="rejected"&&r.status==="negotiating"&&q.customer_response_note.includes("cream")','decline records feedback and negotiation');
 await action('qa-quote-revise');await run('q=K.versions(r)[0];C.add(1,"standard",2)');await action('quote-accept');await action('quote-confirm');
 await run('window.o=K.orders[0]');await assert('location.hash==="#/payment/"+o.id&&o.status==="pending-payment"&&!o.paid','acceptance routes to unpaid cake payment');
 await run('o.deadline=Date.now()-1');await wait(1200);await assert('o.payment==="expired"&&K.activeHolds().length===0','QR expiry releases cake hold');
 await click('[data-commerce=retry-payment]');await assert('o.attempts.length===2&&o.payment==="waiting"','payment retry preserves purchase');
 await click('[data-commerce=simulate-payment]');await assert('o.payment==="detected"&&!document.querySelector("[data-commerce=retry-payment]")','verification locks retry');await wait(1100);
 await assert('o.paid&&o.status==="confirmed"&&C.state.cart[0].quantity===2','cake payment confirms while standard bag stays intact');
 await go('orders/'+await run('o.id'));await assert('document.getElementById("commerce-view").textContent.includes("Owner-managed delivery")&&!document.getElementById("commerce-view").textContent.includes("Courier tracking")','cake order excludes courier tracking');
 await go('account/profile');await action('profile-edit');await fill('#p4-first_name','Elena Updated');await fill('#p4-mobile_number','09179876543');await run('document.getElementById("profile-form").requestSubmit()');await wait();
 await assert('P.current.first_name==="Elena Updated"&&P.current.mobile_number==="+639179876543"','profile save updates shared identity');
 await assert('r.snapshot.contact.name!==P.name()','existing request contact snapshot preserved');
 await action('email-open');await fill('#p4-email','updated@example.com');await fill('#p4-current','BakingMetroCebu2025!');await run('document.getElementById("email-start-form").requestSubmit()');await wait(300);
 await assert('!!document.getElementById("email-verify-form")&&P.current.email!=="updated@example.com"','email waits for verification');
 await fill('#p4-code','000000');await run('document.getElementById("email-verify-form").requestSubmit()');await wait();await assert('P.verification.attempt_count===1&&document.getElementById("phase4-form-error").textContent.includes("Incorrect")','invalid OTP gives inline error');
 await run('window.oldCode=P.verification.code;P.verification.resend_at=0');await action('email-resend');await assert('oldCode!==P.verification.code','resend invalidates prior code');
 await fill('#p4-code',await run('P.verification.code'));await run('document.getElementById("email-verify-form").requestSubmit()');await wait();await assert('P.current.email==="updated@example.com"&&K.request(r.id)===r','verified email preserves request ownership');
 await action('password-open');await fill('#p4-current','wrong');await fill('#p4-next','NewKitchen406!');await fill('#p4-confirm','NewKitchen406!');await run('document.getElementById("password-change-form").requestSubmit()');await wait();await assert('document.getElementById("phase4-form-error").textContent.includes("Incorrect")','wrong current password rejected');
 await fill('#p4-current','BakingMetroCebu2025!');await run('document.getElementById("password-change-form").requestSubmit()');await wait();await assert('!!P.current.password_changed_at&&A.modal===null','password success clears dialog');
 await go('account/addresses');await click('[data-p4=address-default][data-id=work]');await assert('A.addresses.find("work").is_default','address default changes');
 await click('[data-p4=address-remove][data-id=home]');await action('address-archive');await assert('!A.addresses.find("home")&&o.address.address_id==="home"','archive removes future option and preserves order address');
 await action('address-add');await run(`Object.entries({label:'Event Venue',add_line_1:'Event Street',barangay:'Banilad',city:'Cebu City',postal_code:'6000'}).forEach(([k,v])=>{const e=document.querySelector('[name='+k+']');e.value=v;e.dispatchEvent(new Event('input',{bubbles:true}));});Object.assign(P.editor.form,{latitude:10.33,longitude:123.91});document.getElementById('delivery-address-form').requestSubmit()`);await wait();
 await assert('A.addresses.active().some(a=>a.label==="Event Venue"&&a.barangay==="Banilad")','account shared address editor saves structured fields');
 await go('account/notifications');await assert('A.notifications.list().length>=5&&document.getElementById("phase4-view").textContent.includes("Email address changed")','notification history contains connected events');
 await click('[data-p4=notification-filter][data-value=cakes]');await assert('!document.getElementById("phase4-view").textContent.includes("Password changed")','notification category filters');await click('[data-p4=notification-filter][data-value=all]');
 await run('A.email="other@example.com";A.setAuth("signedin")');await go('cake-requests/'+await run('r.id'));await assert('document.getElementById("phase4-view").textContent.includes("not found")&&A.addresses.active().length===0','different customer cannot read prior request or addresses');
 await run('A.email="updated@example.com";A.setAuth("signedin")');await go('cake-requests/'+await run('r.id'));await assert('K.request(r.id)===r','original account restores private records');
 await go('custom-cakes/request/review');await assert('document.getElementById("phase4-view").textContent.includes("Request submitted")','submitted draft cannot create duplicates');
 await run('K.resetDraft()');await go('custom-cakes/request/review');await assert('document.getElementById("phase4-view").textContent.includes("Complete the earlier step")','direct later step enforces prerequisites');
 await run('K.sampleDraft()');
 await go('custom-cakes/request/options');await run('document.querySelector("[data-p4=cake-option][data-id=round]").focus()');await click('[data-p4=cake-option][data-id=round]');await assert('document.activeElement.dataset.id==="round"','keyboard focus survives option rerender');
 await go('account/profile');await action('email-open');await fill('#p4-email','cancelled@example.com');await fill('#p4-current','NewKitchen406!');await run('document.getElementById("email-start-form").requestSubmit();A.closeModal()');await wait(300);await assert('P.verification===null&&P.current.email==="updated@example.com"','closing email dialog invalidates pending async work');
 for(const state of ['loading','error']){await run('P.mock.page='+JSON.stringify(state)+';P.render()');await assert(state==='loading'?'!!document.querySelector(".commerce-skeleton")':'document.getElementById("phase4-view").textContent.includes("Unable to load")','account '+state+' recovery state');await action('retry-page');}
 await action('password-open');await send('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape'});await wait();await assert('A.modal===null&&!document.getElementById("app-shell").inert&&!document.querySelector("#phase4-dialog-body input")','Escape clears sensitive dialog inputs and restores background');
 await action('sign-out');await click('#phase4-view a[href="#/sign-in"]');await fill('#auth-email','updated@example.com');await fill('#auth-password','BakingMetroCebu2025!');await run('document.getElementById("auth-form").requestSubmit()');await wait(850);await assert('A.auth==="guest"&&A.authUI.state.mode==="autherror"','old password fails after password change');
 await fill('#auth-password','NewKitchen406!');await run('document.getElementById("auth-form").requestSubmit()');await wait(850);await assert('A.auth==="signedin"&&P.current.email==="updated@example.com"','new password signs in to the same customer records');
 const routes=['custom-cakes','custom-cakes/request/details','custom-cakes/request/options','custom-cakes/request/references','custom-cakes/request/review','cake-requests','cake-requests/'+await run('r.id'),await run('K.quotePath(q)'),'account/profile','account/addresses','account/notifications','payment/'+await run('o.id')];
 for(const width of [1440,768,390,320]){await send('Emulation.setDeviceMetricsOverride',{width,height:950,deviceScaleFactor:1,mobile:false});for(const route of routes){await go(route);await assert('document.documentElement.scrollWidth<=innerWidth+1',route+' fits '+width);await assert('new Set([...document.querySelectorAll("[id]")].map(e=>e.id)).size===document.querySelectorAll("[id]").length','unique IDs '+route+' at '+width);}}
 await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});await go('custom-cakes/request/options');let shot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});fs.writeFileSync('verification/cake-options-desktop.png',Buffer.from(shot.result.data,'base64'));
 await go(await run('K.quotePath(q)'));shot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});fs.writeFileSync('verification/cake-quotation-desktop.png',Buffer.from(shot.result.data,'base64'));
 await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:false});await go('account/profile');shot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});fs.writeFileSync('verification/account-profile-mobile.png',Buffer.from(shot.result.data,'base64'));
 if(errors.length)throw Error(errors.join('\n'));console.log('COMPLETE '+checks+' Phase 4 browser checks; no uncaught exceptions.');ws.close();
})().catch(e=>{console.error(e);process.exit(1);});
