const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
(async()=>{
const tabs=await(await fetch('http://127.0.0.1:9222/json')).json(),ws=new WebSocket(tabs.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise(r=>ws.onopen=r);let serial=0,count=0;const pending=new Map(),errors=[];
ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){pending.get(m.id)(m);pending.delete(m.id);}else if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.exception?.description||m.params.exceptionDetails.text);};
const send=(method,params={})=>new Promise(r=>{const id=++serial;pending.set(id,r);ws.send(JSON.stringify({id,method,params}));});
const run=async expression=>{const r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.result?.exceptionDetails)throw Error(r.result.exceptionDetails.exception?.description);return r.result.result.value;};
const check=async(expr,label)=>{assert(await run(`(async()=>(${expr}))()`),label);console.log('PASS '+label);count++;},wait=ms=>new Promise(r=>setTimeout(r,ms)),go=async p=>{await run(`location.hash=${JSON.stringify('#/'+p)}`);await wait(100);await run(`K406.$('toast').hidden=true`);};
await send('Runtime.enable');await send('Page.enable');await send('Page.navigate',{url:require('node:url').pathToFileURL(path.resolve('index.html')).href});await wait(1600);
await run('window.A=K406;window.C=A.catalogState;window.O=A.owner;A.session.enter()');await wait(100);
const routes=['products','products/new','products/1/edit','categories','ingredients','cake-options','occasions','staff-accounts','customers','customers/preview-customer','reviews','marketing','reports','notifications','outbox','settings'];
for(const route of routes){await go('owner/'+route);await check(`!!document.querySelector('#owner-view h1')&&!document.querySelector('#owner-view').textContent.includes('Page not found')`,'renders '+route);}
await check(`(()=>{const ids=[...document.querySelectorAll('[id]')].map(e=>e.id);return new Set(ids).size===ids.length})()`,'owner settings use distinct password field labels');
await go('owner/products/999/edit');await check(`A.$('owner-view').textContent.includes('Product not found')`,'invalid product ID has no fallback identity');
await run(`window.category=C.categories[0];window.cv=C.version;window.categoryInput={name:category.name,status:'inactive'};window.savedItem=A.commerce.line(1,'standard',1);A.commerce.state.cart=[savedItem]`);
await check(`C.category(category.id,categoryInput,cv)===''&&!C.visible(A.products[0])&&!A.commerce.cartValid()&&!A.subscriptions.begin(1)`,'category inactivity blocks new purchases and stale carts');
await check(`!!C.category(category.id,{...categoryInput,status:'active'},cv)`,'stale category update rejected');
await run(`C.category(category.id,{...categoryInput,status:'active'},C.version)`);
await check(`C.eligible(1)&&savedItem.price===340`,'category reactivation preserves purchase snapshot');
await check(`!!C.ingredient('flour',{name:'Bread flour',unit:'ml',cost:0.1,threshold:2},C.version)`,'referenced ingredient unit protected');
await run(`window.stock=A.inventory.item('flour').stock;C.ingredient('flour',{name:'Bread flour',unit:'g',cost:0.12,threshold:20},C.version)`);
await check(`A.inventory.item('flour').stock===stock&&A.inventory.item('flour').cost===0.12`,'ingredient definition save preserves stock');
await go('owner/products/new');await run(`window.form=document.querySelector('[data-owner-form=p7-product]');form.elements.name.value='Test loaf';form.elements.description.value='Fresh loaf';form.querySelector('[name=variant-price]').value='200';form.requestSubmit()`);await wait(100);
await check(`A.products.some(p=>p.name==='Test loaf')&&location.hash==='#/owner/products'`,'product create persists through form');
await run(`window.created=A.products.find(p=>p.name==='Test loaf')`);
await check(`!C.eligible(created.id)`,'new product cannot sell without recipe');
await check(`A.pricing.save({id:created.id,variant:'standard',rows:[{id:'flour',quantity:20}],overhead:null,version:A.pricing.version})===''&&C.eligible(created.id)`,'configured recipe enables product');
await check(`C.product(1,{...A.products[0],status:'active',variants:[...A.products[0].variants,{id:'new-size',label:'New size',price:500,status:'active'}]},C.version)===''&&A.inventory.recipe(1,'new-size')===null&&!C.eligible(1,'new-size')`,'new variant on existing product cannot inherit an invented recipe');
await check(`!!C.cake('round',{name:'Round',type:'shape',price:100,available:true,description:'',rows:[{id:'flour',quantity:1},{id:'flour',quantity:2}]},C.version)`,'duplicate cake mapping rejected');
await run(`window.option=A.cakeData.options.find(r=>r.id==='round');window.oldPrice=option.price;C.cake('round',{name:'Round',type:'shape',price:125,available:true,description:'Updated',rows:[{id:'flour',quantity:120}]},C.version)`);
await check(`option.price===12500&&option.ingredients.flour===120`,'cake uses centavos and explicit base quantities');
await check(`!!(await A.staffAccounts.save('',{first_name:'Sam',last_name:'Baker',email:A.session.owner.email,status:'active',password:'Temporary123',confirm:'Temporary123'},0))`,'staff duplicate email denied across roles');
await check(`(await A.staffAccounts.save('',{first_name:'Sam',last_name:'Baker',email:'sam@example.com',status:'active',password:'Temporary123',confirm:'Temporary123'},0))===''`,'staff account creation');
await run(`window.staff=A.staffAccounts.find('sam@example.com');A.setAuth('guest')`);await go('sign-in');await run(`A.$('auth-email').value='sam@example.com';A.$('auth-password').value='Temporary123';A.$('auth-form').requestSubmit()`);await wait(1100);
await check(`A.staff.account===staff&&location.hash==='#/staff/setup'`,'new registry account signs in through shared authentication');
await check(`!A.staff.allowed()&&!!document.querySelector('[data-p7-setup]')`,'setup-required staff has restricted form and no operations');
await check(`(await A.staffAccounts.setup('Temporary123','Changed123','Changed123'))===''&&A.staff.allowed()`,'password setup unlocks active staff');
await check(`C.category(category.id,categoryInput,C.version)!==''&&A.reporting.build()===null&&A.ownerNotifications.outbox().length===0`,'staff denied owner commands and projections');
await run(`A.session.enter();A.staffAccounts.save(staff.id,{first_name:'Sam',last_name:'Baker',email:'sam@example.com',status:'inactive',password:'',confirm:''},A.staffAccounts.version)`);await wait(100);
await run(`A.staff.role='staff'`);await check(`!A.staff.allowed()`,'deactivated staff loses access');
await run(`A.session.leave();A.setAuth('signedin');window.order={id:'P7-REVIEW',customer_id:A.account.id(),type:'standard',paid:true,paidAt:Date.now(),status:'completed',payment:'confirmed',items:[A.commerce.line(1,'standard',2)],fee:100,total:780,fulfillment:{date:A.schedule.today(),method:'pickup'},created:Date.now(),attempts:[]};A.commerce.state.orders.push(order);window.reviewKey=order.id+':'+order.items[0].key`);
await check(`A.feedback.submit(reviewKey,2,'Honest feedback')===''&&!!A.feedback.submit(reviewKey,5,'Duplicate')`,'one feedback per completed purchased item');
await run(`window.feedback=A.feedback.find(reviewKey);A.session.enter()`);
await check(`A.feedback.moderate(feedback.id,'hidden','spam',feedback.version)===''&&A.feedback.public(1).length===0&&feedback.comment==='Honest feedback'`,'moderation hides without changing feedback');
await check(`A.feedback.moderate(feedback.id,'visible','',feedback.version)===''&&A.feedback.public(1).length===1`,'restore uses the same feedback record');
await run(`A.marketing.outcome='failure'`);await check(`!!A.marketing.generate()&&A.marketing.drafts.length===0`,'generation failure creates no fake draft');
await run(`A.marketing.outcome='success';A.marketing.generate();window.draft=A.marketing.drafts[0]`);
await check(`A.ownerNotifications.feed().some(n=>n.path==='owner/marketing/'+draft.id)`,'draft notification links to its record');
await check(`A.marketing.update(draft.id,{caption:'Edited caption',intent:'regenerate'},draft.version)===''&&draft.caption==='Edited caption'&&draft.regenerations===1`,'regeneration retains edited caption');
await check(`A.marketing.update(draft.id,{caption:'Approved caption',intent:'approve'},draft.version)===''&&draft.status==='approved'&&!!A.marketing.update(draft.id,{caption:'Wrong',intent:'reject'},draft.version)`,'approval locks reviewed draft');
await check(`!!A.marketing.occasion('',{name:'Invalid',start:'2026-12-25',end:'2026-12-01',status:'active'},A.marketing.version)`,'occasion date validation');
await run(`A.notifications.emit('p7-test','orders','Receipt','Message','orders/P7-REVIEW',A.account.id(),{email:'sent',sms:'failed'})`);
await check(`new Set(A.ownerNotifications.outbox().map(r=>r.id)).size===A.ownerNotifications.outbox().length`,'outbox uses unique channel identities');
await run(`A.staff.emit('new:P7-REVIEW','orders','New order','staff/production/P7-REVIEW');window.event=A.staff.events.find(e=>e.key==='new:P7-REVIEW');A.ownerNotifications.ack(event.id)`);
await check(`event.read&&event.is_read&&!!event.read_at`,'owner acknowledgement updates shared source');
await run(`A.inventory.items.forEach(i=>i.cost=0.1);window.report=A.reporting.build()`);
await check(`report.receipts.some(r=>r.id==='P7-REVIEW')&&report.revenue===report.products.reduce((n,p)=>n+p.revenue,0)&&report.covered-report.cost===report.products.reduce((n,p)=>n+p.covered-p.cost,0)`,'report receipts and coverage reconcile');
await run(`window.customerBefore=JSON.stringify(A.account.current);window.fakeForm={dataset:{}}`);
await check(`(await A.ownerAccounts.save('profile',fakeForm,{first_name:'Owner',last_name:'Updated'}))===''&&JSON.stringify(A.account.current)===customerBefore`,'owner settings never change customer identity');
await check(`(await A.ownerAccounts.save('email',fakeForm,{email:'newowner@example.com',current:'Kitchen406!'}))===''&&A.session.owner.email!=='newowner@example.com'`,'email stays unchanged before OTP');
await check(`!!(await A.ownerAccounts.save('otp',fakeForm,{code:'wrong'}))&&(await A.ownerAccounts.save('otp',fakeForm,{code:A.ownerAccounts.verification.code}))===''&&A.session.owner.email==='newowner@example.com'`,'OTP validates before owner email update');
await go('owner/products/1/edit');await check(`(()=>{const ids=[...document.querySelectorAll('[id]')].map(e=>e.id);return new Set(ids).size===ids.length})()`,'product editor has unique accessible field IDs');
await run(`window.productForm=document.querySelector('[data-owner-form=p7-product]');productForm.querySelector('[name=variant-label]').value='Unsaved variant';productForm.querySelector('[name=variant-label]').dispatchEvent(new Event('input',{bubbles:true}))`);await go('owner/categories');await go('owner/products/1/edit');
await check(`document.querySelector('[name=variant-label]').value==='Unsaved variant'&&A.variant(1).label!=='Unsaved variant'`,'variant draft restores without mutating saved data');
await run(`document.querySelector('[data-owner=discard]').click()`);await check(`document.querySelector('[name=variant-label]').value===A.variant(1).label`,'discard restores saved variant');
await run(`window.f=document.querySelector('[data-owner-form=p7-product]');A.pricing.setPrice(1,'standard',345,A.pricing.version);f.requestSubmit()`);await wait(100);
await check(`f.querySelector('.owner-error').textContent.includes('Prices or costs changed')&&A.variant(1).price===345`,'stale product editor cannot overwrite Phase 6 price');
await run(`O.drafts.clear();A.commerce.state.cart=[A.commerce.line(1,'standard',1)];A.pricing.setPrice(1,'standard',350,A.pricing.version)`);
await check(`!A.commerce.cartValid()&&A.commerce.priceChanges().length===1`,'new catalog price requires explicit cart acceptance');
await run(`A.commerce.checkout.action('accept-catalog-price',{dataset:{}})`);await check(`A.commerce.state.cart[0].price===350&&A.commerce.priceChanges().length===0&&order.items[0].price===340`,'price acceptance updates cart and preserves paid snapshot');
await go('owner/ingredients');await run(`A.$('owner-query').value='Vanilla';document.querySelector('[data-owner-form=filter]').requestSubmit();document.querySelector('[data-kind=ingredient][data-id=vanilla]').click()`);await check(`A.$('owner-name').value==='Vanilla'&&A.$('owner-unit').value==='g'`,'ingredient modal loads selected record and actual unit');
await run(`A.$('owner-name').value='Unsaved vanilla';A.$('owner-name').dispatchEvent(new Event('input',{bubbles:true}));A.closeModal()`);await check(`!!A.$('owner-dismiss-warning')&&A.inventory.item('vanilla').name==='Vanilla'`,'dirty ingredient dialog protects unsaved changes');
await run(`document.querySelector('[data-owner=discard-modal]').click()`);
await go('owner/cake-options');await run(`document.querySelector('[data-kind=cake][data-id=pink]').click()`);await check(`document.querySelector('[data-bom-id]').value==='tint'&&document.querySelector('[data-bom-quantity]').value==='2'`,'cake editor loads the selected mapping');await run(`A.closeModal(true)`);
await go('owner/categories');await run(`document.querySelector('[data-kind=category]:not([data-id])').click();A.$('owner-name').value='Seasonal specials';document.querySelector('[data-owner-form=p7-category]').requestSubmit()`);await wait(100);
await run(`A.catalog.refresh()`);await check(`A.$('category-tabs').textContent.includes('Seasonal specials')`,'new category reaches customer filters');
await go('owner/marketing/'+await run('draft.id'));await check(`A.$('owner-view').textContent.includes('Approved caption')&&!document.querySelector('[data-owner-form=p7-draft]')`,'approved draft displays saved content without editing controls');
await go('owner/outbox/'+await run(`encodeURIComponent(A.ownerNotifications.outbox()[0].id)`));await check(`A.$('owner-view').textContent.includes(A.ownerNotifications.outbox()[0].id)`,'outbox detail retains selected send identity');
await run(`A.session.leave();A.setAuth('signedin');A.product.show(1)`);await check(`A.$('reviewsPopulatedState').textContent.includes('Honest feedback')`,'customer public feed uses submitted feedback');
await run(`A.session.enter();A.feedback.moderate(feedback.id,'hidden','off_topic',feedback.version);A.product.show(1)`);await check(`!A.$('reviewsPopulatedState').textContent.includes('Honest feedback')`,'hidden review disappears from public rendering');
await run(`A.feedback.moderate(feedback.id,'visible','',feedback.version)`);
for(const width of [1440,768,390,320]){await send('Emulation.setDeviceMetricsOverride',{width,height:900,deviceScaleFactor:1,mobile:width<500});for(const route of routes){await go('owner/'+route);await check(`document.documentElement.scrollWidth<=${width}+1`,'fits '+width+' '+route);}if([1440,390].includes(width)){await go('owner/products');const shot=await send('Page.captureScreenshot',{format:'png'});fs.writeFileSync(path.join('verification','phase7-products-'+width+'.png'),Buffer.from(shot.result.data,'base64'));}}
await run(`A.commerce.reset()`);await check(`A.products.length===20&&!A.products.some(p=>p.name==='Test loaf')&&A.staffAccounts.records.length===1&&A.feedback.records.length===0&&A.marketing.drafts.length===0&&A.session.owner.email==='owner@kitchen406.example'`,'reset restores complete baseline');
assert.deepEqual(errors,[],'browser exceptions');console.log('COMPLETE '+count+' Phase 7 checks; no browser exceptions.');ws.close();
})().catch(e=>{console.error(e);process.exit(1)});
