const fs=require('node:fs');
(async()=>{
 const targets=await(await fetch('http://127.0.0.1:9222/json')).json(),ws=new WebSocket(targets.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise(r=>ws.onopen=r);
 let serial=0,checks=0;const pending=new Map(),errors=[];
 ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){pending.get(m.id)?.(m);pending.delete(m.id);}else if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.exception?.description||m.params.exceptionDetails.text);};
 const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++serial;pending.set(id,resolve);ws.send(JSON.stringify({id,method,params}));setTimeout(()=>{if(pending.delete(id))reject(Error('Timeout '+method));},15000).unref();});
 const run=async expression=>{const m=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(m.result.exceptionDetails)throw Error(m.result.exceptionDetails.exception?.description);return m.result.result.value;};
 const wait=(ms=160)=>new Promise(r=>setTimeout(r,ms));
 const go=async path=>{await run('location.hash='+JSON.stringify('#/'+path));await wait();};
 const click=async selector=>{await run(`document.querySelector(${JSON.stringify(selector)}).click()`);await wait();};
 const action=a=>click('[data-sub="'+a+'"]');
 const assert=async(expr,label)=>{if(!await run(expr))throw Error('FAIL '+label);console.log('PASS '+label);checks++;};
 await send('Runtime.enable');await send('Page.enable');await send('Page.navigate',{url:require('node:url').pathToFileURL(require('node:path').resolve(__dirname,'../index.html')).href});await wait(2600);
 await run(`window.B=K406.subscriptions;window.C=K406.commerce;C.addressMap.load=async()=>{};C.addressMap.mount=()=>{};window.distance=9000;window.google={maps:{importLibrary:async()=>({Route:{computeRoutes:async()=>({routes:[{distanceMeters:distance}]})}})}}`);
 await go('subscriptions');await assert('document.querySelectorAll(".subscription-card").length===4','four subscription products with independent availability');await assert('document.querySelectorAll(".subscription-card")[1].querySelector("button").disabled','full subscription slots block enrollment');
 await click('[data-sub=begin][data-id="4"]');await assert('location.hash==="#/subscription/configure"&&document.getElementById("subscription-view").textContent.includes("Sign in to continue")','guest can browse; configuration requires account');
 await click('#subscription-view a[href="#/sign-in"]');await run('K406.authUI.fill();document.getElementById("auth-form").requestSubmit()');await wait(800);
 await assert('location.hash==="#/subscription/configure"&&B.state.draft.productId===4','sign-in resumes selected enrollment');
 await assert('document.querySelectorAll(".subscription-dates li").length===4&&B.totals().total===1520','configuration shows four weekly dates');
 await click('[data-sub=quantity][data-delta="1"]');await assert('B.totals().total===2640','quantity changes all four products and keeps four fees');
 await click('[data-sub=quantity][data-delta="-1"]');await action('address-next');await assert('location.hash==="#/subscription/address"&&B.deliveryRoute.eligible()','shared route check works for subscription address');
 await action('address-add');await assert('!!document.getElementById("delivery-address-form")','shared address editor opens');
 await run(`Object.entries({label:'Subscription address',add_line_1:'Test St',city:'Mandaue City',postal_code:'6014'}).forEach(([k,v])=>{const e=document.querySelector('[name='+k+']');e.value=v;e.dispatchEvent(new Event('input',{bubbles:true}));});Object.assign(B.addressUI.form,{latitude:10.34,longitude:123.92});document.getElementById('delivery-address-form').requestSubmit()`);await wait();
 await assert('B.address().label==="Subscription address"&&C.state.draft.addressId==="home"','address saved to shared store without changing standard checkout selection');
 await run('distance=10001;B.deliveryRoute.check(true)');await wait();await assert('document.querySelector("[data-sub=review-next]").disabled','outside distance boundary blocks subscription');
 await run('distance=9000;B.deliveryRoute.check(true)');await wait();await action('review-next');
 await assert('location.hash==="#/subscription/review"&&document.getElementById("subscription-view").textContent.includes("1,520")','review has exact full prepaid total');
 await run('C.add(1,"large",2)');await action('pay');await assert('B.state.purchases.length===1&&B.state.records.length===0','payment creates pending enrollment only');
 await run('window.p=B.state.purchases[0];p.deadline=Date.now()-1');await wait(1150);await assert('p.payment==="expired"','subscription payment timer expires');await action('retry-payment');await assert('p.attempts.length===2&&p.payment==="waiting"','retry revalidates and preserves purchase');
 await action('simulate-payment');await wait(1100);await assert('p.paid&&B.state.records.length===1&&C.state.cart[0].quantity===2','activation leaves standard bag untouched');
 await run('window.r=B.state.records[0];B.pay(p,"confirmed")');await assert('r.deliveries.length===4&&C.state.orders.filter(o=>o.subscriptionId===r.id).length===4','one activation creates four linked fulfillment orders');
 await click('#subscription-view a[href^="#/subscriptions/SUB-"]');await assert('document.querySelectorAll(".subscription-dates li").length===4','subscription detail displays four obligations');
 await go('my-subscriptions');await assert('document.querySelectorAll(".subscription-list-card").length===1','active subscription appears in customer list');
 await go('subscriptions/'+await run('r.id')+'/defer/'+await run('r.deliveries[2].id'));await click('[data-sub=defer-option][data-value=week]');await action('defer-confirm');
 await assert('K406.modal==="subscription-confirm-modal"&&document.getElementById("app-shell").inert','deferment confirmation uses accessible dialog');
 await action('defer-apply');await assert('r.deliveries[2].date==="2026-11-13"&&r.deferments.length===1','Next Week collision moves beyond final delivery');
 await assert('C.state.orders.find(o=>o.id===r.deliveries[2].orderId).fulfillment.date==="2026-11-13"','deferment updates linked order');
 await go('subscriptions/'+await run('r.id')+'/defer/'+await run('r.deliveries[3].id'));await assert('document.querySelector("[data-sub=defer-confirm]").disabled','second deferment blocked');
 await go('orders/'+await run('r.deliveries[0].orderId'));await assert('document.getElementById("commerce-view").textContent.includes("Included in prepaid subscription")&&!document.querySelector("[data-commerce=cancel-order]")','fulfillment order cannot charge subscription again');
 await go('payment/'+await run('r.deliveries[0].orderId'));await assert('document.getElementById("commerce-view").textContent.includes("already included")&&!document.querySelector("[data-commerce=payment-preview]")','direct payment route cannot create a new charge for prepaid fulfillment');
 await run('r.deliveries.forEach(d=>C.setStatus(C.state.orders.find(o=>o.id===d.orderId),"completed"))');await go('subscriptions/'+await run('r.id'));await assert('r.status==="completed"&&!!document.querySelector("[data-sub=again]")','completion requires all four deliveries');
 await action('again');await assert('location.hash==="#/subscription/configure"&&B.state.draft.purchaseId===undefined','Subscribe Again opens a new draft');
 await go('subscriptions/unknown');await assert('document.getElementById("subscription-view").textContent.includes("not found")','unknown subscription reference handled');
 await go('product/1');await click('[data-purchase=subscription]');await assert('document.getElementById("addToCartBtn").textContent.includes("Configure")','product page offers separate subscription action');await click('#addToCartBtn');await assert('B.state.draft.productId===1&&location.hash==="#/subscription/configure"','product configuration carries identity');
 await action('address-next');await assert('document.querySelectorAll("#address-map").length===1','subscription address mounts a single map');
 await run('C.state.draft.method="delivery";C.state.draft.date="2026-10-16"');await go('checkout/address');
 await assert('document.querySelectorAll("#address-map").length===1&&document.getElementById("subscription-view").childElementCount===0','switching to standard checkout removes obsolete subscription controls');
 await go('subscription/address');await assert('document.querySelectorAll("#address-map").length===1&&document.getElementById("commerce-view").childElementCount===0','returning to subscription removes obsolete standard controls');
 await action('review-next');await run('B.mock.price="updated";B.render()');await assert('document.querySelector("[data-sub=pay]").disabled','subscription price change blocks payment');await action('accept-price');await assert('B.totals().unit===360&&p.snapshot.unit===280','accepted price changes draft while paid snapshot stays fixed');
 await action('pay');await run('window.pendingEnrollment=B.state.purchases[0]');await go('my-subscriptions');await assert('!!document.querySelector(".subscription-pending")&&B.state.records.length===1','new unpaid setup stays outside active subscriptions');
 await action('cancel-setup');await assert('pendingEnrollment.payment==="cancelled"&&B.state.records.length===1','cancel setup preserves paid subscription');
 await action('samples');await assert('B.state.records.filter(s=>s.fixture).length===3','sample management records load with linked fulfillment orders');
 await go('subscriptions');await click('[data-sub=category][data-value=pastries]');await assert('document.querySelectorAll(".subscription-card").length===1','subscription category filter');await click('[data-sub=category][data-value=all]');
 const routes=['subscriptions','subscription/configure','subscription/address','subscription/review','subscription/payment/'+await run('p.id'),'my-subscriptions','subscriptions/'+await run('r.id'),'subscriptions/'+await run('r.id')+'/defer/'+await run('r.deliveries[0].id')];
 for(const width of [1440,768,390,320]){await send('Emulation.setDeviceMetricsOverride',{width,height:950,deviceScaleFactor:1,mobile:false});for(const route of routes){await go(route);await assert('document.documentElement.scrollWidth<=innerWidth+1',route+' fits '+width);}}
 await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});await go('subscriptions');let shot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});fs.writeFileSync('verification/subscriptions-desktop.png',Buffer.from(shot.result.data,'base64'));
 await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:false});await go('subscriptions/'+await run('r.id'));shot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});fs.writeFileSync('verification/subscription-details-mobile.png',Buffer.from(shot.result.data,'base64'));
 await assert('new Set([...document.querySelectorAll("[id]")].map(e=>e.id)).size===document.querySelectorAll("[id]").length','unique DOM IDs');
 if(errors.length)throw Error(errors.join('\n'));console.log('COMPLETE '+checks+' subscription browser checks; no uncaught exceptions.');ws.close();
})().catch(e=>{console.error(e);process.exit(1);});
