const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
let checks=0;
function setup(){
 const ctx={K406:{auth:'signedin',toast(){},$(){return {classList:{toggle(){}}};}},Date,Intl,setTimeout,clearTimeout};ctx.window=ctx;vm.createContext(ctx);
 for(const file of ['products','product-data','scheduling','commerce-state','subscription-state'])vm.runInContext(fs.readFileSync('app/'+file+'.js','utf8'),ctx);
 const A=ctx.K406,B=A.subscriptions,C=A.commerce,D=A.schedule;B.deliveryRoute={eligible:()=>true,reset(){}};B.begin(4);return {A,B,C,D};
}
function test(label,fn){fn();checks++;console.log('PASS '+label);}
test('prices and four dispatches independent of quantity',()=>{const {B}=setup();assert.equal(B.totals().total,1520);B.state.draft.quantity=2;assert.equal(B.totals().total,2640);B.begin(1);assert.equal(B.totals().total,1760);});
test('cutoff boundary and Sunday follow configuration',()=>{const {D,C}=setup();const items=[C.line(1)];D.config.clock='2026-10-14T15:59:59+08:00';assert.equal(D.standard('2026-10-16',items),'');D.config.clock='2026-10-14T16:00:00+08:00';assert.equal(D.standard('2026-10-16',items),'Cutoff');assert.equal(D.standard('2026-10-18',items),'');assert.equal(D.standard('2026-10-14',items),'Passed');});
test('standard capacity groups variants and uses a separate pool',()=>{const {D,C}=setup();assert.equal(D.standard('2026-10-16',[C.line(1,'standard',6),C.line(1,'large',5)]),'Capacity');D.reserve('sub',1,10,['2026-10-16'],true);assert.equal(D.standard('2026-10-16',[C.line(1)]),'');});
test('mixed cart observes each product lead time and batch days',()=>{const {D,C}=setup();D.config.productRules[2]={leadDays:5,batches:[2,5]};assert.equal(D.standard('2026-10-16',[C.line(1)]),'');assert.equal(D.standard('2026-10-16',[C.line(1),C.line(2)]),'Cutoff');assert.equal(D.standard('2026-10-20',[C.line(1),C.line(2)]),'');});
test('all four weeks checked before payment; expired holds release',()=>{const {B,D}=setup();D.reserve('other',4,10,['2026-10-30'],true);assert.equal(B.createPurchase(),null);D.release('other');const p=B.createPurchase();assert.equal(D.allocations.length,4);assert.equal(B.state.records.length,0);B.pay(p,'expired');assert.equal(D.allocations.length,0);assert(B.retry(p));assert.equal(p.attempts.length,2);});
test('confirmation is repeat safe and leaves standard cart intact',()=>{const {B,C,D}=setup();C.state.cart=[C.line(1,'large',2)];const p=B.createPurchase();const r=B.pay(p,'confirmed');B.pay(p,'confirmed');assert.equal(B.state.records.length,1);assert.equal(r.deliveries.length,4);assert.equal(C.state.orders.length,4);assert.equal(C.state.cart[0].quantity,2);assert.equal(C.state.cart[0].price,480);assert(D.allocations.every(a=>a.confirmed));assert(C.state.orders.every(o=>o.prepaid&&o.reference===p.id));});
test('paid snapshots survive product and saved address edits',()=>{const {B,C}=setup();const p=B.createPurchase();B.pay(p,'confirmed');B.variant().price=900;C.state.addresses[0].city='Changed';assert.equal(p.snapshot.total,1520);assert.equal(p.snapshot.unit,280);assert.equal(p.snapshot.address.city,'Mandaue City');});
test('verification prevents edits, cancellation, and retry',()=>{const {B}=setup();const p=B.createPurchase();B.pay(p,'detected');assert(!B.change());assert(!B.cancel(p));assert(!B.retry(p));assert.equal(B.createPurchase(),null);});
test('late payment after released hold requires resolution when full',()=>{const {B,D}=setup();const p=B.createPurchase();B.pay(p,'expired');D.reserve('other',4,10,p.snapshot.dates,true);B.pay(p,'confirmed');assert.equal(p.payment,'resolution');assert(p.paid);assert.equal(B.state.records.length,0);assert(!B.retry(p));});
test('Next Week collision moves to the first available week after cycle',()=>{const {B,D}=setup();const r=B.pay(B.createPurchase(),'confirmed'),d=r.deliveries[2];assert.equal(B.deferTarget(r,d,'week'),'2026-11-13');D.config.blocked=['2026-11-13'];assert.equal(B.deferTarget(r,d,'week'),'2026-11-20');assert.equal(B.defer(r,d,'week'),'');assert.equal(d.date,'2026-11-20');assert.equal(r.deliveries[3].date,'2026-11-06');assert.equal(r.deliveries.length,4);assert.equal(r.deferments[0].originalDate,'2026-10-30');assert(B.defer(r,d,'day'));});
test('failed deferment preserves original allocation and allowance',()=>{const {B,D}=setup();const r=B.pay(B.createPurchase(),'confirmed'),d=r.deliveries[2];D.config.blocked=['2026-10-31'];assert(B.defer(r,d,'day'));assert.equal(d.date,'2026-10-30');assert.equal(r.deferments.length,0);assert.equal(D.allocations.find(a=>a.cycle===3).date,d.date);});
test('deferment respects cutoff, preparation status, and current capacity',()=>{const {B,C,D}=setup();const r=B.pay(B.createPurchase(),'confirmed'),d=r.deliveries[2],order=C.state.orders.find(o=>o.id===d.orderId);order.status='preparing';assert(B.defer(r,d,'day'));order.status='confirmed';D.config.clock='2026-10-28T16:00:00+08:00';assert(B.defer(r,d,'day'));assert.equal(r.deferments.length,0);});
test('four fulfilled orders complete a subscription; deferred is not fulfilled',()=>{const {B,C}=setup();const r=B.pay(B.createPurchase(),'confirmed');B.defer(r,r.deliveries[2],'day');r.deliveries.slice(0,3).forEach(d=>C.state.orders.find(o=>o.id===d.orderId).status='completed');B.sync(r);assert.equal(r.status,'active');C.state.orders.find(o=>o.id===r.deliveries[3].orderId).status='completed';B.sync(r);assert.equal(r.status,'completed');});
console.log('COMPLETE '+checks+' subscription state checks.');
