/* Catalog definitions share the product and material authorities used by checkout. */
(() => {
const A=K406,copy=x=>JSON.parse(JSON.stringify(x));
const baseline=copy(A.products),cakeBaseline=copy(A.cakeData);
const C=A.catalogState={categories:[],version:0};
C.baselineVariant=(id,variant)=>baseline.some(p=>p.id===Number(id)&&p.variants.some(v=>v.id===variant));
C.bind=p=>Object.defineProperty(p,'available',{configurable:true,enumerable:true,get:()=>A.inventory.productAvailable(p.id),set:value=>A.inventory.catalogEnabled.set(p.id,value)});
C.reset=()=>{A.products.splice(0,A.products.length,...copy(baseline));A.inventory.catalogEnabled=new Map(baseline.map(p=>[p.id,p.available]));A.products.forEach(C.bind);C.categories=[...new Map(A.products.map(p=>[p.category,{id:p.category,name:p.categoryLabel,status:'active'}])).values()];C.version=0;A.cakeData.options=copy(cakeBaseline.options);A.cakeData.addons=copy(cakeBaseline.addons);C.metadata?.();};
C.variantStatus=v=>['inactive','unavailable'].includes(v.status)?'unavailable':'available';
C.price=p=>{const variants=p.variants.filter(v=>C.variantStatus(v)==='available');return variants.length?Math.min(...variants.map(v=>v.price)):null;};
C.priceLabel=p=>C.price(p)===null?'No available variants':A.commerce.money(C.price(p));
C.stamp=(r,creator=false)=>{const now=Date.now();r.created_at??=now;r.updated_at=now;if(creator)r.created_by_admin_id??=A.session.owner.id;return r;};
C.metadata=()=>{C.categories.forEach(r=>C.stamp(r));A.products.forEach(p=>{C.stamp(p);p.variants.forEach(v=>{v.status=C.variantStatus(v);C.stamp(v);});});A.inventory.items.forEach(r=>C.stamp(r));[...A.cakeData.options,...A.cakeData.addons].forEach(r=>{C.stamp(r,true);if(r.type)r.scale_factor??=null;});};
C.reset();C.metadata();
C.guard=version=>!A.session.ownerAllowed()?'Owner access required.':Number(version)!==C.version?'Definitions changed. Reopen the editor.':'';
C.visible=p=>!!p&&p.status!=='inactive'&&C.categories.some(c=>c.id===p.category&&c.status==='active');
C.eligible=(id,variant='standard')=>{const p=A.products.find(p=>p.id===Number(id)),v=A.variant(id,variant);return C.visible(p)&&p.available&&!!v&&C.variantStatus(v)==='available'&&!!A.inventory.recipe(Number(id),variant);};
C.record=(kind,r,parent=null)=>{const stamp={created_at:r.created_at,updated_at:r.updated_at};if(kind==='variant')return {...stamp,variant_id:parent.id+':'+r.id,product_id:parent.id,size:r.label,final_price:r.price,suggested_price:A.pricing.cost(parent.id,r.id)?.suggested??null,utility_overhead:A.pricing.overheads.get(parent.id+':'+r.id)??null,status:C.variantStatus(r)};if(kind==='product')return {...stamp,product_id:r.id,category_id:r.category,name:r.name,description:r.description,img_url:r.image,subscription_eligible:r.subscription,status:r.status||'active'};if(kind==='category')return {...stamp,category_id:r.id,category_name:r.name,status:r.status};if(kind==='ingredient')return {...stamp,inventory_id:r.id,name:r.name,unit:r.unit,stock_on_hand:r.stock,reorder_threshold:r.threshold,cost_per_unit:r.cost,status:({'Available':'available','Low stock':'low_stock','Out of stock':'unavailable'})[A.inventory.status(r)]};return {...stamp,[r.type?'option_id':'addon_id']:r.id,created_by_admin_id:r.created_by_admin_id,option_type:r.type,scale_factor:r.scale_factor??null,name:r.name,option_name:r.name,price:r.price/100,status:r.available?'available':'unavailable'};};
C.emailUsed=(email,except)=>[...A.account.records,...(A.staffAccounts?.records||[]),A.session.owner].some(r=>r!==except&&r.email.toLowerCase()===email.toLowerCase());
C.category=(id,input,version)=>{const error=C.guard(version);if(error)return error;const r=C.categories.find(r=>r.id===id),name=input.name.trim();if(id&&!r)return 'Category not found.';if(!name||C.categories.some(c=>c!==r&&c.name.toLowerCase()===name.toLowerCase()))return 'Enter a unique category name.';const saved=r||{id:crypto.randomUUID()};Object.assign(saved,{name,status:input.status==='inactive'?'inactive':'active'});C.stamp(saved);if(!r)C.categories.push(saved);A.products.filter(p=>p.category===saved.id).forEach(p=>p.categoryLabel=name);C.version++;return '';};
C.product=(id,input,version)=>{const error=C.guard(version);if(error)return error;const p=A.products.find(p=>p.id===Number(id));if(id&&!p)return 'Product not found.';if(!['active','inactive'].includes(input.status)||!input.name.trim()||!C.categories.some(c=>c.id===input.category)||!input.variants.length)return 'Name, category, and at least one variant are required.';
 const ids=new Set();for(const v of input.variants){if(!/^[a-zA-Z0-9_-]+$/.test(v.id)||!['active','inactive','available','unavailable'].includes(v.status||'available')||ids.has(v.id)||!v.label.trim()||!Number.isFinite(v.price)||v.price<=0)return 'Variants need unique IDs, labels, and positive prices.';ids.add(v.id);}
 if(p?.variants.some(v=>!ids.has(v.id)))return 'Retain existing variants and mark them inactive to preserve references.';
 if(input.image&&!/^(assets\/|data:image\/(png|jpeg|webp);base64,)/.test(input.image))return 'Use a local PNG, JPEG, or WebP image.';
 const saved=p||{id:Math.max(0,...A.products.map(p=>p.id))+1,available:true};Object.assign(saved,{name:input.name.trim(),description:input.description.trim(),category:input.category,categoryLabel:C.categories.find(c=>c.id===input.category).name,status:input.status,subscription:input.subscription,variants:input.variants.map(v=>C.stamp({...v,status:C.variantStatus(v),created_at:p?.variants.find(old=>old.id===v.id)?.created_at})),image:input.image||'assets/braided-chocolate-babka.png'});C.stamp(saved);saved.price=C.priceLabel(saved);saved.variant=saved.variants.map(v=>v.label).join(' / ');saved.catalogEdited=true;if(!p){A.products.push(saved);C.bind(saved);}C.version++;A.pricing.version++;return '';};
C.ingredient=(id,input,version)=>{const error=C.guard(version);if(error)return error;const i=A.inventory.item(id);if(id&&!i)return 'Ingredient not found.';if(!input.name.trim()||A.inventory.items.some(r=>r!==i&&r.name.toLowerCase()===input.name.trim().toLowerCase()))return 'Enter a unique ingredient name.';if(!['g','ml','pcs'].includes(input.unit)||![input.cost,input.threshold].every(n=>Number.isFinite(n)&&n>=0))return 'Choose a base unit and nonnegative cost and threshold.';
 if(i&&i.unit!==input.unit){const references=A.products.some(p=>p.variants.some(v=>Object.hasOwn(A.inventory.recipe(p.id,v.id)||{},id)))||[...A.cakeData.options,...A.cakeData.addons].some(o=>Object.hasOwn(o.ingredients,id));if(i.stock||references||[...A.inventory.requirementRows.values()].some(r=>r.inventory_id===id)||A.inventory.movements.some(m=>m.ingredientId===id)||[...A.inventory.reservations.values()].some(r=>Object.hasOwn(r.materials,id)))return 'Referenced units cannot be changed. Create a new ingredient instead.';}
 const saved=i||{id:crypto.randomUUID(),stock:0,opening:0};Object.assign(saved,input,{name:input.name.trim()});C.stamp(saved);if(!i)A.inventory.items.push(saved);C.version++;A.pricing.version++;A.inventory.notify();return '';};
C.cake=(id,input,version)=>{const error=C.guard(version);if(error)return error;const all=[...A.cakeData.options,...A.cakeData.addons],old=all.find(r=>r.id===id);if(id&&!old)return 'Cake option not found.';if(!input.name.trim()||!['addon',...A.cakeData.categories].includes(input.type)||!Number.isFinite(input.price)||input.price<0)return 'Enter a name, type, and nonnegative price.';if(old&&(old.type||'addon')!==input.type)return 'The type of an existing option cannot change.';const ingredients={};for(const row of input.rows){if(!A.inventory.item(row.id)||Object.hasOwn(ingredients,row.id)||!Number.isFinite(row.quantity)||row.quantity<=0)return 'Use each ingredient once with a positive base-unit quantity.';ingredients[row.id]=row.quantity;}const saved=old||{id:crypto.randomUUID()};Object.assign(saved,{name:input.name.trim(),description:input.description,price:Math.round(input.price*100),available:input.available,ingredients});C.stamp(saved,true);if(input.type!=='addon'){saved.type=input.type;saved.scale_factor??=null;}if(!old)(input.type==='addon'?A.cakeData.addons:A.cakeData.options).push(saved);C.version++;return '';};
})();
