(() => {
const A=K406,C=A.commerce,E=A.escape;
const U=C.ui={};
U.link=(path,label,primary=false)=>`<a class="btn${primary?' primary':''}" href="#/${path}">${E(label)}</a>`;
U.button=(action,label,disabled=false,extra='')=>`<button type="button" class="btn${['checkout','fulfillment-next','address-next','pay','simulate-payment','check-payment','retry-payment','accept-price'].includes(action)?' primary':''}" data-commerce="${action}" ${disabled?'disabled':''} ${extra}>${E(label)}</button>`;
U.alert=(text,error=false)=>`<div class="alert${error?' error':''}" role="status">${E(text)}</div>`;
U.panel=(title,body,action='')=>`<section class="commerce-card"><div class="commerce-card-heading"><h2>${title}</h2>${action}</div>${body}</section>`;
U.date=value=>value?new Date(value+'T12:00:00').toLocaleDateString('en-PH',{weekday:'short',month:'short',day:'numeric',year:'numeric'}):'Choose a date';
U.address=a=>a?`<p>${E([a.add_line_1,a.add_line_2,a.city,a.postal_code].filter(Boolean).join(', '))}</p>${a.landmark?`<p class="muted">Landmark: ${E(a.landmark)}</p>`:''}${a.is_default?'<p class="muted">Default address</p>':''}`:'<p>Select a delivery address.</p>';
U.items=(items,editable=false)=>items.map((i,index)=>`<article class="commerce-item"><img src="${E(i.image)}" alt="${E(i.name)}"><div>${i.productId?`<a class="item-name" href="#/product/${i.productId}">${E(i.name)}</a>`:`<strong>${E(i.name)}</strong>`}<p class="muted">${E(i.variant)} · ${C.money(i.price)} each</p>${editable?`<div class="quantity-control">${U.button('decrease','−',i.quantity<=1,`data-index="${index}" aria-label="Decrease ${E(i.name)} quantity"`)}<span aria-label="Quantity">${i.quantity}</span>${U.button('increase','+',i.quantity>=i.max,`data-index="${index}" aria-label="Increase ${E(i.name)} quantity"`)}${U.button('remove','Remove',false,`data-index="${index}" aria-label="Remove ${E(i.name)}"`)}</div>`:`<p class="muted">Qty: ${i.quantity}</p>`}${editable&&!i.available?U.alert('Currently unavailable. Remove this item to continue.',true):i.quantity>i.max?U.alert('Reduce quantity to '+i.max+' or fewer.',true):''}</div><strong>${C.money(i.price*i.quantity)}</strong></article>`).join('');
U.summary=(order=null,includeFulfillment=true)=>{const s=C.state,items=order?.items||s.cart,fee=includeFulfillment?(order?order.fee:C.fee()):0,method=order?.fulfillment.method||s.draft.method;return U.panel('Order summary',`<p class="muted">${C.count(items)} items · ${items.length} products</p>${U.items(items)}<dl class="commerce-totals"><div><dt>Items subtotal</dt><dd>${C.money(C.subtotal(items))}</dd></div>${includeFulfillment&&method?`<div><dt>${method==='pickup'?'Pickup':'Delivery fee'}</dt><dd>${fee===null?'Calculated after address':C.money(fee)}</dd></div>`:''}<div class="grand-total"><dt>${includeFulfillment&&(fee===null||!method)?'Subtotal':'Total'}</dt><dd>${C.money(order&&includeFulfillment?order.total:C.subtotal(items)+(method&&fee!==null?fee:0))}</dd></div></dl>`);};
U.fulfillment=(o=null,includeAddress=true)=>{const d=o?.fulfillment||C.state.draft;return `<p><strong>${d.method==='pickup'?'Bakery pickup':'Courier delivery'}</strong></p><p>${U.date(d.date)}</p>${!includeAddress?'':d.method==='pickup'?'<p>Kitchen406 · Banilad, Metro Cebu</p><p class="muted">Demo collection window: 10:00 AM–2:00 PM. Exact pickup address requires bakery confirmation.</p>':U.address(o?.address||C.address())}`;};
U.page=(title,subtitle,body)=>`<div class="commerce-heading"><h1 tabindex="-1">${E(title)}</h1><p>${E(subtitle)}</p></div>${body}`;
U.columns=(main,aside)=>`<div class="commerce-grid"><div class="commerce-stack">${main}</div><aside class="commerce-stack">${aside}</aside></div>`;
U.empty=(title,message,action=U.link('shop','Browse the shop',true))=>U.panel(title,`<p>${E(message)}</p><div class="commerce-actions">${action}</div>`);
U.status=o=>`<span class="order-badge ${['payment-failed','payment-resolution'].includes(o.status)?'attention':''}">${E(o.status.replaceAll('-',' '))}</span>`;
U.field=(name,label,value='',required=true,type='text')=>`<div class="field"><label for="address-${name}">${label}${required?' *':''}</label><input id="address-${name}" name="${name}" value="${E(value??'')}" ${required?'required':''} type="${type}" maxlength="200"></div>`;
})();
