/* Phase 7 catalog forms use the same owner cards, controls and material commands. */
(() => {
const A=K406,V=A.ownerUI,E=A.escape,C=A.catalogState;
const X=A.ownerCatalog={selected:new Set(),layout:'table'};
const attrs=id=>`data-id="${E(id)}"`;
const options=[['active','Active'],['inactive','Inactive']];
const textarea=(name,label,value)=>`<div class="field"><label for="owner-${name}">${E(label)}</label><textarea id="owner-${name}" name="${name}">${E(value||'')}</textarea></div>`;
X.textarea=textarea;
const edit=(kind,id)=>V.button('p7-edit','Edit',`data-kind="${kind}" ${attrs(id)}`);
const form=(kind,id,body)=>V.form('p7-'+kind,body,`${attrs(id||'')} data-version="${C.version}" data-pricing-version="${A.pricing.version}"`);
const filtered=rows=>rows.filter(r=>!A.owner.filters.query||r.name.toLowerCase().includes(A.owner.filters.query.toLowerCase())).sort((a,b)=>a.name.localeCompare(b.name)*(A.owner.filters.sort==='name-desc'?-1:1));
const stateSelect=states=>V.select('state','State',[['all','All states'],...states],A.owner.filters.state||'all');
const list=(title,rows,heads,row,kind)=>{const type=r=>r.type||'addon',state=r=>kind==='cake'?(r.available?'available':'unavailable'):kind==='ingredient'?A.inventory.status(r):r.status;const states=kind==='cake'?[['available','Available'],['unavailable','Unavailable']]:kind==='ingredient'?['Available','Low stock','Out of stock'].map(s=>[s,s]):options;rows=rows.filter(r=>(!A.owner.filters.state||A.owner.filters.state==='all'||state(r)===A.owner.filters.state)&&(kind!=='cake'||A.owner.filters.type==='all'||type(r)===A.owner.filters.type));return V.intro(title,'Manage the shared bakery definitions.',V.button('p7-edit','Add '+kind,`data-kind="${kind}"`))+V.collectionFilters(kind==='cake'?[...A.cakeData.categories,'addon'].map(s=>[s,s]):[],stateSelect(states))+V.panel(title,V.paged(filtered(rows),items=>V.table(heads,items.map(row))));};
X.variantRow=(v={id:'',label:'',price:'',status:'active'})=>{const prefix='variant-'+crypto.randomUUID();return `<div class="p7-variant-row">${V.field('variant-id','Variant ID',v.id,'text','required')}${V.field('variant-label','Label',v.label,'text','required')}${V.field('variant-price','Price (PHP)',v.price,'number','required min="0.01" step="0.01"')}${V.select('variant-status','Status',[['available','Available'],['unavailable','Unavailable']],C.variantStatus(v))}</div>`.replaceAll('id="owner-variant-',`id="${prefix}-`).replaceAll('for="owner-variant-',`for="${prefix}-`);};
X.productEditor=()=>{const id=A.owner.parts[2],p=id==='new'?null:A.products.find(p=>String(p.id)===id);if(id!=='new'&&(!p||A.owner.parts[3]!=='edit'))return V.panel('Product not found','<p>Choose a product from the list.</p>',V.link('products','Products'));
 return V.intro(p?'Edit '+p.name:'Add product','Changes apply to future purchases.',V.link('products','Back to products'))+V.panel('Product details',form('product',p?.id,V.field('name','Product name',p?.name||'','text','required maxlength="120"')+textarea('description','Description',p?.description)+V.select('category','Category',C.categories.map(c=>[c.id,c.name]),p?.category)+V.select('status','Catalog status',options,p?.status||'active')+V.select('subscription','Subscription eligible',[['false','No'],['true','Yes']],String(p?.subscription||false))+`<div class="field"><label for="owner-image-file">Product image (PNG, JPEG, WebP; up to 2 MB)</label><input id="owner-image-file" type="file" accept="image/png,image/jpeg,image/webp" data-p7-image><input type="hidden" name="image" value="${E(p?.image||'')}"><img class="p7-preview" data-p7-preview src="${E(p?.image||'assets/braided-chocolate-babka.png')}" alt="Product preview"></div><h3>Variants</h3><p>Retain existing IDs. Deactivate a variant to preserve purchase references.</p><div id="p7-variants">${(p?.variants||[{id:'standard',label:'Standard',price:'',status:'active'}]).map(X.variantRow).join('')}</div>`+V.button('p7-add-variant','Add variant')+'<p>New variants require a recipe before they can be purchased.</p>'+V.link('recipes','Recipes & costing')+V.button('discard','Discard draft')));};
X.products=()=>{
 if(A.owner.parts[2])return X.productEditor();
 const f=A.owner.filters,rows=filtered(A.products.filter(p=>(f.type==='all'||p.category===f.type)&&(!f.state||f.state==='all'||(p.status||'active')===f.state)&&(!f.subscription||f.subscription==='all'||String(p.subscription)===f.subscription)));
 const select=p=>`<input type="checkbox" data-p7-select="${p.id}" aria-label="Select ${E(p.name)}" ${X.selected.has(p.id)?'checked':''}>`;
 return V.intro('Products','Catalog status, selling prices and recipe readiness.',V.link('products/new','Add product'))+V.collectionFilters(C.categories.map(c=>[c.id,c.name]),stateSelect(options)+V.select('subscription','Subscription',[['all','All products'],['true','Eligible'],['false','Not eligible']],f.subscription||'all'))+
 `<div class="staff-toolbar">${V.button('p7-layout',X.layout==='table'?'Show cards':'Show table')}${V.button('p7-select-page','Select visible page')}${V.button('p7-bulk','Activate selected','data-status="active"')}${V.button('p7-bulk','Deactivate selected','data-status="inactive"')}<span>${X.selected.size} selected</span></div>`+
 V.panel('Products',V.paged(rows,items=>X.layout==='table'?V.table(['Select','Product','Category','Price','Status','Actions'],items.map(p=>`<tr><td>${select(p)}</td><td>${E(p.name)}</td><td>${E(p.categoryLabel)}</td><td>${E(C.priceLabel(p))}</td><td>${V.badge(p.status||'active')}<p>${p.variants.filter(v=>C.eligible(p.id,v.id)).length} purchasable variants</p></td><td>${V.link('products/'+p.id+'/edit','Edit')}</td></tr>`)):`<div class="p7-grid">${items.map(p=>V.panel(p.name,`<label>${select(p)} Select product</label><img class="p7-preview" src="${E(p.image)}" alt="${E(p.name)}"><p>${E(p.categoryLabel)} · ${E(p.status||'active')}</p><p>${E(C.priceLabel(p))}</p>`,V.link('products/'+p.id+'/edit','Edit'))).join('')}</div>`));
};
X.categories=()=>list('Categories',C.categories,['Category','Products','Status','Actions'],c=>`<tr><td>${E(c.name)}</td><td>${A.products.filter(p=>p.category===c.id).length}</td><td>${V.badge(c.status)}</td><td>${edit('category',c.id)}${V.button('p7-category-products','View products',attrs(c.id))}</td></tr>`,'category');
X.ingredients=()=>list('Ingredients',A.inventory.items,['Ingredient','Unit','Unit cost','Stock state','Actions'],i=>`<tr><td>${E(i.name)}</td><td>${E(i.unit)}</td><td>${V.money(i.cost)}</td><td>${V.badge(A.inventory.status(i))}</td><td>${edit('ingredient',i.id)}${V.link('inventory/'+i.id,'Stock & history')}</td></tr>`,'ingredient');
X.cakes=()=>list('Cake options & add-ons',[...A.cakeData.options,...A.cakeData.addons],['Name','Type','Price','Availability','Actions'],r=>`<tr><td>${E(r.name)}</td><td>${E(r.type||'addon')}</td><td>${V.money(r.price/100)}</td><td>${V.badge(r.available?'available':'unavailable')}</td><td>${edit('cake',r.id)}</td></tr>`,'cake');
X.open=(kind,id)=>{let r,body;if(kind==='category'){r=C.categories.find(r=>r.id===id);body=V.field('name','Category name',r?.name||'','text','required')+V.select('status','Status',options,r?.status||'active');}
 else if(kind==='ingredient'){r=A.inventory.item(id);body=V.field('name','Ingredient name',r?.name||'','text','required')+V.select('unit','Base unit',[['g','Grams (g)'],['ml','Milliliters (ml)'],['pcs','Pieces (pcs)']],r?.unit||'g')+V.field('cost','Cost per base unit (PHP)',r?.cost??'','number','required min="0" step="0.0001"')+V.field('threshold','Low-stock threshold',r?.threshold??0,'number','required min="0" step="0.001"')+'<p>Stock movements belong in Inventory. Referenced units cannot be changed.</p>';}
 else if(kind==='cake'){r=[...A.cakeData.options,...A.cakeData.addons].find(r=>r.id===id);body=V.field('name','Name',r?.name||'','text','required')+V.select('type','Type',[...A.cakeData.categories,'addon'].map(t=>[t,t]),r?.type||'addon')+textarea('description','Description',r?.description)+V.field('price','Price (PHP)',(r?.price||0)/100,'number','required min="0" step="0.01"')+V.select('available','Availability',[['true','Available'],['false','Unavailable']],String(r?.available??true))+'<p>Explicit quantities in base units; size quantities are already sized. No additional multiplier applies.</p><div id="owner-bom">'+Object.entries(r?.ingredients||{}).map(([id,quantity])=>A.ownerInventory.row(id,quantity)).join('')+'</div>'+V.button('add-bom','Add ingredient');}
 else return false;if(id&&!r){A.toast('Record not found.');return true;}A.owner.open('Edit '+kind,form(kind,id,body));return true;};
X.save=(kind,form,data)=>{const id=form.dataset.id,version=Number(form.dataset.version);if(['product','ingredient'].includes(kind)&&Number(form.dataset.pricingVersion)!==A.pricing.version)return 'Prices or costs changed. Discard this draft and reopen the editor.';if(kind==='product')return C.product(id,{...data,subscription:data.subscription==='true',variants:[...form.querySelectorAll('.p7-variant-row')].map(row=>({id:row.querySelector('[name=variant-id]').value.trim(),label:row.querySelector('[name=variant-label]').value.trim(),price:Number(row.querySelector('[name=variant-price]').value),status:row.querySelector('[name=variant-status]').value}))},version);
 if(kind==='category')return C.category(id,data,version);if(kind==='ingredient')return C.ingredient(id,{name:data.name,unit:data.unit,cost:Number(data.cost),threshold:Number(data.threshold)},version);if(kind==='cake')return C.cake(id,{...data,price:Number(data.price),available:data.available==='true',rows:[...form.querySelectorAll('.owner-bom-row')].map(row=>({id:row.querySelector('[data-bom-id]').value,quantity:Number(row.querySelector('[data-bom-quantity]').value)}))},version);return null;};
})();
