/* Original 20 catalog fixtures. */
K406.products = [
        {
          id: 1,
          name: "Braided Chocolate Babka",
          category: "breads",
          categoryLabel: "Breads",
          variant: "2 sizes",
          description: "Soft braided loaf with chocolate filling.",
          price: "From ₱340",
          subscription: true,
          available: true,
          image: "assets/product-14.jpg"
        },
        {
          id: 2,
          name: "Country Sourdough Batard",
          category: "breads",
          categoryLabel: "Breads",
          variant: "750g loaf",
          description: "Naturally fermented crusty loaf.",
          price: "₱280",
          subscription: true,
          available: true,
          image: "assets/product-17.jpg"
        },
        {
          id: 3,
          name: "Cardamom Kouign-Amann",
          category: "pastries",
          categoryLabel: "Pastries",
          variant: "Box of 2 or 4",
          description: "Layered sweet spiced pastry.",
          price: "From ₱160",
          subscription: false,
          available: true,
          image: "assets/product-19.jpg"
        },
        {
          id: 4,
          name: "Japanese Shokupan (Milk Bread)",
          category: "breads",
          categoryLabel: "Breads",
          variant: "Half or Full loaf",
          description: "Soft square pullman loaf.",
          price: "From ₱220",
          subscription: true,
          available: true,
          image: "assets/product-13.jpg"
        },
        {
          id: 5,
          name: "Ube Halaya Croissant",
          category: "pastries",
          categoryLabel: "Pastries",
          variant: "Single piece",
          description: "Flaky layered pastry with sweet ube filling.",
          price: "₱190",
          subscription: false,
          available: true,
          image: "assets/product-16.jpg"
        },
        {
          id: 6,
          name: "Vanilla Bean Sea Salt Canelé",
          category: "pastries",
          categoryLabel: "Pastries",
          variant: "Box of 4",
          description: "Caramelized French pastry with custard center.",
          price: "From ₱240",
          subscription: false,
          available: false,
          image: "assets/product-6.jpg"
        },
        {
          id: 7,
          name: "Rosemary Focaccia",
          category: "breads",
          categoryLabel: "Breads",
          variant: "Quarter sheet",
          description: "Olive oil bread topped with rosemary and sea salt.",
          price: "₱260",
          subscription: false,
          available: true,
          image: "assets/product-18.jpg"
        },
        {
          id: 8,
          name: "Cultured Herb Honey Butter",
          category: "pantry",
          categoryLabel: "Pantry",
          variant: "200g jar",
          description: "Cultured herb butter spread.",
          price: "₱180",
          subscription: false,
          available: true,
          image: "assets/product-20.jpg"
        },
        {
          id: 9,
          name: "Pandesal",
          category: "breads",
          categoryLabel: "Breads",
          variant: "Pack of 6",
          description: "Soft Filipino bread. Pack of 6.",
          price: "₱140",
          subscription: true,
          available: true,
          image: "assets/product-16.jpg"
        },
        {
          id: 10,
          name: "Cinnamon Rolls",
          category: "pastries",
          categoryLabel: "Pastries",
          variant: "Box of 4",
          description: "Soft rolls with cinnamon filling. Box of 4.",
          price: "₱290",
          subscription: false,
          available: true,
          image: "assets/product-19.jpg"
        },
        {
          id: 11,
          name: "Dark Chocolate Brownies",
          category: "pastries",
          categoryLabel: "Pastries",
          variant: "Box of 6",
          description: "Rich chocolate brownies.",
          price: "₱320",
          subscription: false,
          available: true,
          image: "assets/product-14.jpg"
        },
        {
          id: 12,
          name: "Crispy Butter Cookies",
          category: "pantry",
          categoryLabel: "Pantry",
          variant: "Pack of 12",
          description: "Crispy butter cookies.",
          price: "₱210",
          subscription: false,
          available: true,
          image: "assets/product-20.jpg"
        },
        {
          id: 13,
          name: "Brioche Burger Buns",
          category: "breads",
          categoryLabel: "Breads",
          variant: "Pack of 4",
          description: "Golden glazed brioche buns.",
          price: "₱180",
          subscription: true,
          available: true,
          image: "assets/product-13.jpg"
        },
        {
          id: 14,
          name: "Banana Walnut Loaf",
          category: "breads",
          categoryLabel: "Breads",
          variant: "Standard loaf",
          description: "Moist banana loaf with toasted walnuts.",
          price: "₱310",
          subscription: false,
          available: true,
          image: "assets/product-14.jpg"
        },
        {
          id: 15,
          name: "Kalamata Olive Sourdough",
          category: "breads",
          categoryLabel: "Breads",
          variant: "750g loaf",
          description: "Naturally fermented sourdough with olives.",
          price: "₱330",
          subscription: true,
          available: false,
          image: "assets/product-17.jpg"
        },
        {
          id: 16,
          name: "Twice-Baked Almond Croissant",
          category: "pastries",
          categoryLabel: "Pastries",
          variant: "Single piece",
          description: "Flaky croissant topped with sliced almonds.",
          price: "₱195",
          subscription: false,
          available: true,
          image: "assets/product-16.jpg"
        },
        {
          id: 17,
          name: "Traditional Baguette",
          category: "breads",
          categoryLabel: "Breads",
          variant: "Single baguette",
          description: "Crispy crust with airy crumb interior.",
          price: "₱150",
          subscription: false,
          available: true,
          image: "assets/product-17.jpg"
        },
        {
          id: 18,
          name: "Roasted Garlic Focaccia",
          category: "breads",
          categoryLabel: "Breads",
          variant: "Quarter sheet",
          description: "Golden focaccia with confit garlic cloves.",
          price: "₱270",
          subscription: false,
          available: true,
          image: "assets/product-18.jpg"
        },
        {
          id: 19,
          name: "Salted Caramel Tart",
          category: "pastries",
          categoryLabel: "Pastries",
          variant: "Single tart",
          description: "Crisp pastry shell with smooth caramel filling.",
          price: "₱175",
          subscription: false,
          available: true,
          image: "assets/product-19.jpg"
        },
        {
          id: 20,
          name: "Whipped Sea Salt Butter",
          category: "pantry",
          categoryLabel: "Pantry",
          variant: "200g jar",
          description: "Smooth salted butter for table spreading.",
          price: "₱170",
          subscription: false,
          available: true,
          image: "assets/product-20.jpg"
        }
      ];
