(() => {
const A=K406,S=A.staff,I=A.inventory,E=A.escape,U=A.ui;
const links=[['','Dashboard'],['production','Production Queue'],['inventory','Inventory'],['movements','Stock Movements'],['recipes','Recipes'],['calendar','Production Calendar'],['notifications','Notifications'],['settings','Settings']];
const btn=(action,label,extra='',primary=false)=>U.button({action,label,extra,variant:primary?'primary':''});
const link=(path,label)=>`<a class="btn" href="#/${E(path)}">${E(label)}</a>`;
const panel=(title,bodyHtml,actionsHtml='')=>U.panel({title,bodyHtml,actionsHtml});
const field=(name,label,value='',type='text',extra='')=>U.field({name,label,value,type,extra});
const select=(name,label,values,value)=>`<div class="field"><label for="staff-${name}">${label}</label><select id="staff-${name}" data-staff-filter="${name}">${values.map(([v,l])=>`<option value="${E(v)}" ${String(value)===String(v)?'selected':''}>${E(l)}</option>`).join('')}</select></div>`;
const date=d=>A.commerce.ui.date(d),stamp=n=>new Date(n).toLocaleString('en-PH',{timeZone:'Asia/Manila'});
const badge=U.badge,empty=(message='No records match your filters.')=>panel('Nothing to show',`<p>${E(message)}</p>`);
const table=(heads,rows)=>`<div class="staff-table-wrap" tabindex="0" aria-label="Scrollable table"><table class="staff-table"><thead><tr>${heads.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`;
const nav=()=>`<aside class="staff-nav"><strong>${E(S.name())}</strong><p class="muted">Bakery Staff</p><nav aria-label="Staff workspace">${links.map(([path,label])=>`<a href="#/staff${path?'/'+path:''}" ${path===(S.parts[1]||'')?'aria-current="page"':''}>${label}</a>`).join('')}</nav></aside>`;
S.show=parts=>{if(S.parts[1]!==parts[1]){S.generation++;S.query='';S.type='all';S.status='active';S.range='all';S.page=1;}S.parts=parts;S.render();};
S.filtered=()=>S.list().filter(o=>{
 const q=S.query.toLowerCase();return (!q||[o.id,...o.items.map(i=>i.name+' '+i.variant)].join(' ').toLowerCase().includes(q))&&(S.type==='all'||o.type===S.type)&&(S.status==='all'||S.status==='active'&&['confirmed','preparing','ready'].includes(o.status)||S.status===o.status)&&(S.range==='all'||S.range==='today'&&o.date===A.schedule.today()||S.range==='tomorrow'&&o.date===A.schedule.add(A.schedule.today(),1));
}).sort((a,b)=>a.date.localeCompare(b.date)||a.id.localeCompare(b.id));
const filters=()=>`<div class="staff-toolbar">${field('query','Search orders or products',S.query,'search','data-staff-filter="query"')}${select('type','Order type',[['all','All types'],['standard','Standard'],['subscription','Subscription delivery'],['cake','Custom cake']],S.type)}${select('status','Status',[['active','Active'],['all','All statuses'],['confirmed','Confirmed'],['preparing','Preparing'],['ready','Ready'],['completed','Completed']],S.status)}${select('range','Fulfillment date',[['all','All dates'],['today','Today'],['tomorrow','Tomorrow']],S.range)}</div>`;
const method=o=>o.method==='pickup'?'Bakery pickup':o.type==='cake'?'Owner delivery':'Courier delivery';
const action=o=>{const target=o.status==='confirmed'?'preparing':o.status==='preparing'?'ready':o.status==='ready'&&o.method==='pickup'?'completed':null;return target?btn('transition',({preparing:'Start preparation',ready:'Mark Ready',completed:'Complete Pickup'})[target],`data-id="${E(o.id)}" data-target="${target}" data-version="${o.version}"`,true):'';};
const card=o=>`<article class="commerce-card staff-order"><h3><a class="text-link" href="#/staff/production/${E(o.id)}">${E(o.id)}</a></h3>${badge(o.type==='subscription'?'Subscription delivery':o.type==='cake'?'Custom cake':'Standard')} ${badge(o.status)}<p>${date(o.date)} · ${method(o)}</p><ul>${o.items.map(i=>`<li>${E(i.name)} · ${E(i.variant)} × ${i.quantity}</li>`).join('')}</ul>${o.subscriptionId?`<p>${E(o.subscriptionId)} · ${cycleLabel(o.id)}</p>`:''}${o.materialIssue?`<p class="alert error">${E(o.materialIssue)}</p>`:''}<div class="staff-actions">${action(o)}${link('staff/production/'+o.id,'Details')}</div></article>`;
function cycleLabel(id){for(const r of [...A.subscriptions.state.records,...[...A.account.buckets.values()].flatMap(b=>b.subscription?.records||[])]){const d=r.deliveries.find(d=>d.orderId===id);if(d)return 'Delivery '+d.cycle+' of 4'+(d.date!==d.originalDate?' (moved from '+date(d.originalDate)+')':'');}return 'Weekly fulfillment';}
function dashboard(){const today=A.schedule.today(),end=A.schedule.add(today,S.range==='week'?6:0),orders=S.list().filter(o=>o.date>=today&&o.date<=end),alerts=I.items.filter(i=>I.available(i.id)<=i.threshold);
 return U.pageIntro({title:'Staff Dashboard',subtitle:'Production and fulfillment at Kitchen406.'})+`<div class="staff-toolbar">${select('range','Fulfillment range',[['today','Today'],['week','Next 7 Days']],S.range==='week'?'week':'today')}</div><div class="staff-stats">${[['Confirmed',orders.filter(o=>o.status==='confirmed').length],['Preparing',orders.filter(o=>o.status==='preparing').length],['Ready',orders.filter(o=>o.status==='ready').length],['Current stock alerts',alerts.length]].map(([label,value])=>U.stat({label,value})).join('')}</div><div class="staff-stack">${panel('Attention needed',alerts.length?alerts.map(i=>`<p>${E(i.name)}: ${I.available(i.id)} ${i.unit} available · ${badge(I.status(i))}</p>`).join(''):'<p>No current stock alerts.</p>',link('staff/inventory','View inventory'))}${panel('Fulfillment in selected range',orders.length?`<div class="staff-grid">${orders.map(card).join('')}</div>`:'<p>No orders scheduled in this range.</p>',link('staff/production','Full queue'))}${panel('Upcoming production',S.list().filter(o=>o.date>end&&o.status!=='completed').slice(0,5).map(o=>`<p>${date(o.date)} · <a class="text-link" href="#/staff/production/${E(o.id)}">${E(o.id)}</a> · ${method(o)}</p>`).join('')||'<p>No upcoming work.</p>',link('staff/calendar','Calendar'))}</div>`;
}
function queue(){const orders=S.filtered();return U.pageIntro({title:'Production Queue',subtitle:'Prepare paid orders, stage finished products, and complete pickups.'})+filters()+`<p class="muted">${orders.length} orders match this scope.</p>`+(orders.length?`<div class="staff-grid">${orders.map(card).join('')}</div>`:empty());}
function materialTable(m,orderId){return m?table(['Ingredient','Required','Reserved for this order','Available for new orders','Shortage for this order'],Object.entries(m).map(([id,q])=>{const i=I.item(id),r=I.reservations.get(orderId),reserved=r&&I.active(r)?r.materials[id]||0:0,used=r?.status==='consumed';return `<tr><td>${E(i?.name||id)}</td><td>${q} ${E(i?.unit||'')}</td><td>${orderId?reserved:'N/A'}</td><td>${i?I.available(id):'N/A'} ${E(i?.unit||'')}</td><td>${orderId&&!used&&i?Math.max(0,Math.round((q-I.available(id,orderId))*1000)/1000):0}</td></tr>`})): '<p class="alert error">Recipe requirements are not configured. Preparation is unavailable.</p>';}

function details(){const o=S.list().find(o=>o.id===S.parts[2]);if(!o)return empty('Order not found or unavailable for production.');
 const raw=S.orders().find(x=>x.id===o.id),q=raw.quotationId?A.cakes.state.quotations.find(q=>q.id===raw.quotationId):null;
 const copy=A.cakes.productionCopy?.(q);
 // Only owner-reviewed copies are exposed to staff.
 const spec=q?panel('Approved cake specifications',`<div class="staff-specs">${q.snapshot.options.map(x=>`<p><strong>${E(x.type)}</strong><br>${E(x.name)}</p>`).join('')}</div>${q.snapshot.addons.map(x=>`<p>${E(x.name)} × ${x.quantity}</p>`).join('')}${copy?`<h3>Approved production instructions</h3><p>${E(copy.notes)}</p><div class="staff-specs">${copy.images.map((url,n)=>`<img src="${E(url)}" alt="Approved design reference ${n+1}">`).join('')}</div><p class="muted">Reviewed ${stamp(copy.reviewed_at)}</p>`:'<p class="alert">Production instructions and references await owner review.</p>'}`):'';
 return U.pageIntro({title:o.id,subtitle:date(o.date)+' · '+method(o),actionsHtml:link('staff/production','Back to queue')})+`<div class="staff-stack">${card(o)}${spec}${panel('Ingredient requirements',materialTable(o.requirements,o.id)+`<p class="staff-note">${['preparing','ready','completed'].includes(o.status)?'Ingredients recorded as used when preparation started.':'Starting preparation records this order’s reserved ingredients as used.'}</p>`)}${panel('Fulfillment',`<p>${method(o)}</p><p>${o.method==='pickup'?'Mark the pickup Completed only after handing over the order.':o.type==='cake'?'The owner handles delivery.':'Courier status: '+E(o.courier)+'. Booking is managed by the owner after readiness.'}</p>`)}${panel('Production history',o.history.length?`<ol class="staff-history">${o.history.map(h=>`<li>${badge(h.status)} · ${E(h.changed_by_account_id===S.account.id?S.name():h.actor)} · ${stamp(h.at)}</li>`).join('')}</ol>`:'<p>No staff transitions recorded in this preview.</p>')}${panel('Preparation checklist',`<p class="muted">Optional local reminders; these checks are not an audit record.</p>${['Check quantities and specifications','Check packaging','Stage for handoff'].map(t=>`<p><label><input type="checkbox"> ${t}</label></p>`).join('')}`)}</div>`;
}
function inventory(){let items=I.items.filter(i=>i.name.toLowerCase().includes(S.query.toLowerCase())&&(S.status==='active'||S.status==='all'||I.status(i)===S.status));items.sort((a,b)=>S.sort==='name'?a.name.localeCompare(b.name):I.available(a.id)-I.available(b.id));return U.pageIntro({title:'Inventory',subtitle:'Physical stock, active reservations, and quantities available for new commitments.'})+`<div class="staff-toolbar">${field('query','Search ingredients',S.query,'search','data-staff-filter="query"')}${select('status','Stock status',[['all','All stock'],['Available','Available'],['Low stock','Low stock'],['Out of stock','Out of stock']],['Available','Low stock','Out of stock'].includes(S.status)?S.status:'all')}${select('sort','Sort',[['available','Lowest available'],['name','Name']],S.sort||'available')}</div>`+panel('Base ingredients',table(['Ingredient','Unit','On hand','Reserved','Available','Threshold','Status','Actions'],items.map(i=>`<tr><td>${btn('ingredient',i.name,`data-id="${i.id}"`)}</td><td>${i.unit}</td><td>${i.stock}</td><td>${I.reserved(i.id)}</td><td>${I.available(i.id)}</td><td>${i.threshold}</td><td>${badge(I.status(i))}</td><td>${btn('restock','Restock',`data-id="${i.id}"`)} ${btn('adjust','Adjust',`data-id="${i.id}"`)}</td></tr>`)))+`<p>${items.length} ingredients · quantities are shown in their base units.</p>`;}
function movements(){let rows=I.movements.filter(m=>(!S.ingredient||m.ingredientId===S.ingredient)&&(S.movementType==='all'||m.type===S.movementType)&&(S.source==='all'||m.performed_by_account_id===S.source)&&(!S.from||new Date(m.at).toLocaleDateString('en-CA',{timeZone:'Asia/Manila'})>=S.from)&&(!S.to||new Date(m.at).toLocaleDateString('en-CA',{timeZone:'Asia/Manila'})<=S.to));const pages=Math.max(1,Math.ceil(rows.length/10));S.page=Math.min(S.page,pages);return U.pageIntro({title:'Stock Movements',subtitle:'An attributed history of physical inventory changes.'})+`<div class="staff-toolbar">${select('ingredient','Ingredient',[['','All ingredients'],...I.items.map(i=>[i.id,i.name])],S.ingredient)}${select('movementType','Type',[['all','All types'],['restock','Restock'],['consumption','Consumption'],['consumption_reversal','Consumption reversal'],['adjustment','Adjustment']],S.movementType)}${select('source','Recorded by',[['all','All actors'],...[...new Map(I.movements.map(m=>[m.performed_by_account_id,m.performed_by_account_id===S.account.id?S.name():m.actor])).entries()]],S.source)}${field('from','From',S.from,'date','data-staff-filter="from"')}${field('to','Through',S.to,'date','data-staff-filter="to"')}</div>`+(rows.length?panel('Movement history',table(['Time','Ingredient','Type','Change','Recorded by','Source / reason','Details'],rows.slice((S.page-1)*10,S.page*10).map(m=>`<tr><td>${stamp(m.at)}</td><td>${E(I.item(m.ingredientId).name)}</td><td>${E(m.type.replaceAll('_',' '))}</td><td>${m.delta>0?'+':''}${m.delta} ${I.item(m.ingredientId).unit}</td><td>${E(m.performed_by_account_id===S.account.id?S.name():m.actor)}</td><td>${m.orderId?`<a class="text-link" href="#/staff/production/${E(m.orderId)}">${E(m.orderId)}</a>`:E(m.reason||'Restock')}</td><td>${btn('movement','View',`data-id="${m.id}"`)}</td></tr>`)))+`<div class="staff-pager">${btn('page-prev','Previous',S.page===1?'disabled':'')}<span>Page ${S.page} of ${pages} · ${rows.length} movements</span>${btn('page-next','Next',S.page===pages?'disabled':'')}</div>`:empty('No physical stock movements in this range.'));}
function recipes(){const products=A.products.filter(p=>p.name.toLowerCase().includes(S.query.toLowerCase()));const p=products.find(p=>p.id===Number(S.recipeId))||products[0];if(p)S.recipeId=p.id;const v=p?.variants.find(v=>v.id===S.variant)||p?.variants[0];if(v)S.variant=v.id;return U.pageIntro({title:'Recipes',subtitle:'Read-only ingredient requirements for each product variant.'})+`<div class="staff-toolbar">${field('query','Search products',S.query,'search','data-staff-filter="query"')}${select('recipeId','Product',products.map(p=>[p.id,p.name]),S.recipeId)}${select('variant','Variant',(p?.variants||[]).map(v=>[v.id,v.label]),S.variant)}</div>`+(p?panel(p.name,`<p>Ingredients for 1 ${E(v.label)}.</p>${materialTable(I.recipe(p.id,v.id))}`,link('staff/inventory','View inventory')):empty());}
function calendar(){const chosen=S.calendarDate,week=A.schedule.week(chosen),first=chosen.slice(0,7)+'-01',start=S.calendarView==='month'?A.schedule.week(first):week;const orders=S.list().filter(o=>S.includeCompleted||o.status!=='completed').filter(o=>(!S.calendarStatus||S.calendarStatus==='all'||o.status===S.calendarStatus)&&(S.type==='all'||o.type===S.type)&&(!S.query||[o.id,...o.items.map(i=>i.name)].join(' ').toLowerCase().includes(S.query.toLowerCase())));const days=S.calendarView==='month'?42:7;const matches=(o,d)=>(S.calendarBasis==='preparation'?o.preparationDate:o.date)===d;
 const grid=S.calendarView==='day'?'':`<div class="staff-table-wrap" tabindex="0" aria-label="Scrollable production calendar"><div class="staff-calendar ${S.calendarView}">${Array.from({length:days},(_,n)=>{const d=A.schedule.add(start,n),list=orders.filter(o=>matches(o,d)),blocked=A.schedule.config.blocked.includes(d);return `<section class="staff-day ${blocked?'blocked':''}" ${d===chosen?'aria-current="date"':''}>${btn('day',d,`data-date="${d}"`)}<p>${list.length} orders${blocked?' · Blocked date':''}</p>${list.map(o=>`<a href="#/staff/production/${E(o.id)}">${E(o.id)}<br>${E(o.items.map(i=>i.name+' ×'+i.quantity).join(', '))}<br>${badge(o.status)}</a>`).join('')}</section>`}).join('')}</div></div>`;
 const selected=orders.filter(o=>matches(o,chosen));return U.pageIntro({title:'Production Calendar',subtitle:'View fulfillment commitments or subscription preparation days separately.'})+`<div class="staff-calendar-head"><div class="staff-actions">${btn('calendar-prev','Previous')}${btn('today','Today')}${btn('calendar-next','Next')}</div><strong>${S.calendarView==='month'?chosen.slice(0,7):date(chosen)}</strong><div class="staff-actions">${['day','week','month'].map(v=>btn('calendar-view',v,`data-view="${v}" aria-pressed="${v===S.calendarView}"`)).join('')}</div></div><div class="staff-toolbar">${select('type','Type',[['all','All types'],['standard','Standard'],['subscription','Subscription'],['cake','Custom cake']],S.type)}${select('calendarStatus','Status',[['all','All statuses'],['confirmed','Confirmed'],['preparing','Preparing'],['ready','Ready'],['completed','Completed']],S.calendarStatus||'all')}${select('calendarBasis','Dates to show',[['fulfillment','Fulfillment'],['preparation','Subscription preparation']],S.calendarBasis||'fulfillment')}${field('query','Search commitments',S.query,'search','data-staff-filter="query"')}<label><input type="checkbox" data-staff-filter="includeCompleted" ${S.includeCompleted?'checked':''}> Show Completed</label></div>${grid}<div class="staff-stack" style="margin-top:24px">${panel('Agenda · '+date(chosen),`<p>${selected.length} orders · ${selected.reduce((n,o)=>n+o.items.reduce((n,i)=>n+i.quantity,0),0)} sellable units</p>`+(selected.length?`<div class="staff-grid">${selected.map(card).join('')}</div>`:'<p>No commitments for this date.</p>'))}</div>`;
}
function notifications(){const events=S.events.filter(e=>S.notificationFilter==='all'||S.notificationFilter==='unread'&&!e.read||e.type===S.notificationFilter);return U.pageIntro({title:'Notifications',subtitle:'Acknowledging marks an update as read for the team.',actionsHtml:btn('read-all','Mark all as read')})+`<div class="staff-toolbar">${select('notificationFilter','Filter',[['all','All'],['unread','Unread'],['orders','Orders'],['inventory','Inventory']],S.notificationFilter)}<p>${S.events.filter(e=>!e.read).length} unread</p></div>`+panel('Operational updates',events.map(e=>`<article class="staff-notification ${e.read?'':'unread'}"><strong>${E(e.message)}</strong><p class="muted">${stamp(e.at)}</p><div class="staff-actions">${e.read?badge('Acknowledged'):btn('read','Acknowledge',`data-id="${e.id}"`)}${link(e.path,'View details')}</div></article>`).join('')||'<p>No matching updates.</p>');}
function settings(){return U.pageIntro({title:'Staff Account',subtitle:'Manage your permitted account details.'})+`<div class="staff-stack">${panel('Profile',`<form class="staff-form" data-staff-form="profile">${field('first_name','First name',S.account.first_name,'text','required maxlength="80"')}${field('last_name','Last name',S.account.last_name,'text','required maxlength="80"')}${field('email','Login email',S.account.email,'email','readonly')}<p class="muted">Your role and login email are managed by the owner.</p><p class="field-error staff-error" role="alert"></p><button class="btn primary">Save changes</button></form>`)}${panel('Change password',`<form class="staff-form" data-staff-form="password">${field('current','Current password','','password','required autocomplete="current-password"')}${field('next','New password','','password','required minlength="8" autocomplete="new-password"')}${field('confirm','Confirm password','','password','required autocomplete="new-password"')}<p class="muted">Use at least 8 characters with letters and numbers.</p><p class="field-error staff-error" role="alert"></p><button class="btn primary">Update password</button></form>`)}</div>`;}
S.render=()=>{if(A.route!=='staff')return;const root=A.$('staff-view');if(!root)return;
 if(A.auth==='signedin'&&S.role==='staff'&&S.account.status==='active'&&!S.account.setup&&A.staffAccounts){root.innerHTML=A.staffAccounts.setupPage();return;}
 const focus=document.activeElement,selection=focus?.selectionStart,id=root.contains(focus)?focus.id:null;
 if(!S.allowed()){root.innerHTML=U.pageIntro({title:'Staff access required',subtitle:A.auth==='signedin'?'This account does not have active staff workspace access.':'Sign in with an owner-provisioned staff account.'})+panel('Restricted workspace','<p>Use your assigned staff account. Preview staff accounts are available through Mock Controls.</p>'+link('sign-in','Sign in')+link('shop','Back to shop'));return;}
 const view=S.parts[1]||'',body=S.mode==='loading'?panel('Loading','<p role="status">Loading operational records…</p>'):S.mode==='error'?panel('Unable to load','<p>Records could not be loaded. Please retry.</p>'+btn('retry','Retry')):S.mode==='empty'?empty():({'':dashboard,production:()=>S.parts[2]?details():queue(),inventory,movements,recipes,calendar,notifications,settings}[view]||(()=>empty('Page not found.')))();
 root.innerHTML=`<div class="staff-layout">${nav()}<div class="staff-main">${body}</div></div>`;
 if(id){const node=A.$(id);node?.focus({preventScroll:true});try{node?.setSelectionRange(selection,selection);}catch{}}
};
S.open=(title,body)=>{A.$('staff-dialog-title').textContent=title;A.$('staff-dialog-body').innerHTML=body;A.openModal('staff-modal');};
function stockForm(id,type,original=''){const i=I.item(id);if(!i)return;S.formKey=crypto.randomUUID();S.open(type==='restock'?'Record restock':'Adjust physical count',`<form class="staff-form" data-staff-form="stock" data-id="${i.id}" data-type="${type}"><p>${E(i.name)} · On hand: ${i.stock} ${i.unit}</p>${field('quantity',type==='restock'?'Quantity added ('+i.unit+')':'Physical count ('+i.unit+')',type==='restock'?'':i.stock,'number',`required min="${type==='restock'?'0.001':'0'}" step="${i.unit==='pcs'?'1':'0.001'}"`)}${type==='adjustment'?'<div class="field"><label for="staff-reason">Reason</label><select id="staff-reason" name="reason">'+['miscount','spoilage','damage','theft','correction','other'].map(v=>`<option ${original&&v==='correction'?'selected':''}>${v}</option>`).join('')+'</select></div>':''}${field('notes','Note',original?'Correction for '+original:'')}<p id="staff-stock-preview" class="staff-note">Enter the counted quantity to review the change.</p><p class="field-error staff-error" role="alert"></p><button class="btn primary">Confirm ${type==='restock'?'restock':'adjustment'}</button></form>`);}
document.addEventListener('input',e=>{if(e.target.id==='staff-quantity'){const form=e.target.form,i=I.item(form.dataset.id),q=Number(e.target.value),delta=form.dataset.type==='restock'?q:q-i.stock;A.$('staff-stock-preview').textContent=`Change: ${delta>0?'+':''}${Math.round(delta*1000)/1000} ${i.unit}. New on hand: ${Math.round((i.stock+delta)*1000)/1000} ${i.unit}.`;}});
document.addEventListener('change',e=>{const key=e.target.dataset.staffFilter;if(!key||!S.allowed())return;S[key]=e.target.type==='checkbox'?e.target.checked:e.target.value;S.page=1;S.render();});
document.addEventListener('click',e=>{
 const el=e.target.closest('[data-staff]');if(!el||el.disabled)return;const actionName=el.dataset.staff,id=el.dataset.id;
 if(actionName==='enter'){S.enter();return;}if(actionName==='customer'){S.leave();return;}if(!S.allowed())return;
 if(actionName==='signout'){S.generation++;S.role='customer';A.setAuth('guest');location.hash='#/staff';window.dispatchEvent(new HashChangeEvent('hashchange'));return;}
 if(actionName==='seed')S.seed();
 if(actionName==='retry')S.mode='normal';
 if(actionName==='transition'){S.formKey=crypto.randomUUID();S.open(el.textContent,`<p>${el.dataset.target==='preparing'?'This records the reserved ingredients as used.':el.dataset.target==='completed'?'Confirm that this pickup has been handed over.':'Confirm the order is prepared and staged.'}</p><p class="field-error staff-error" role="alert"></p>${btn('confirm-transition','Confirm',`data-id="${E(id)}" data-target="${el.dataset.target}" data-version="${el.dataset.version}"`,true)}`);return;}
 if(actionName==='confirm-transition'){const error=S.transition(id,el.dataset.target,Number(el.dataset.version),S.formKey);if(error){document.querySelector('#staff-modal .staff-error').textContent=error;return;}A.closeModal();A.toast('Order updated.');}
 if(actionName==='restock'||actionName==='adjust'){stockForm(id,actionName==='restock'?'restock':'adjustment');return;}
 if(actionName==='ingredient'){const i=I.item(id);S.open(i.name,`<p>On hand ${i.stock} ${i.unit} · Reserved ${I.reserved(id)} · Available ${I.available(id)}</p><h3>Recent movements</h3>${I.movements.filter(m=>m.ingredientId===id).slice(0,5).map(m=>`<p>${stamp(m.at)} · ${m.delta} ${i.unit} · ${E(m.performed_by_account_id===S.account.id?S.name():m.actor)}</p>`).join('')||'<p>No movements.</p>'}<div class="staff-actions">${btn('restock','Restock',`data-id="${id}"`)}${btn('adjust','Adjust',`data-id="${id}"`)}</div>`);return;}
 if(actionName==='movement'){const m=I.movements.find(m=>m.id===id);S.open(m.id,`<p>${E(I.item(m.ingredientId).name)} · ${E(m.type)}</p><p>Before: ${m.before} · Change: ${m.delta} · After: ${m.after}</p><p>${E(m.performed_by_account_id===S.account.id?S.name():m.actor)} · ${stamp(m.at)}</p><p>${E(m.notes)}</p>${m.type==='adjustment'?btn('correction','Record correction',`data-id="${m.id}"`):''}`);return;}
 if(actionName==='correction'){const m=I.movements.find(m=>m.id===id);stockForm(m.ingredientId,'adjustment',m.id);return;}
 if(actionName==='page-prev')S.page=Math.max(1,S.page-1);if(actionName==='page-next')S.page++;
 if(actionName==='day')S.calendarDate=el.dataset.date;
 if(actionName==='calendar-view')S.calendarView=el.dataset.view;
 if(actionName==='today')S.calendarDate=A.schedule.today();
 if(actionName==='calendar-prev'||actionName==='calendar-next'){const direction=actionName==='calendar-prev'?-1:1;if(S.calendarView==='month'){const d=new Date(S.calendarDate.slice(0,7)+'-01T12:00:00Z');d.setUTCMonth(d.getUTCMonth()+direction);S.calendarDate=d.toISOString().slice(0,10);}else S.calendarDate=A.schedule.add(S.calendarDate,direction*(S.calendarView==='week'?7:1));}
 if(actionName==='read'||actionName==='read-all'){if(S.saveError){A.toast('Acknowledgement could not be saved. Retry.');return;}S.events.filter(x=>!x.read&&(actionName==='read-all'||x.id===id)).forEach(x=>{x.read=true;x.is_read=true;x.read_at=Date.now();});}
 S.render();A.shell.sync();
});
document.addEventListener('submit',async e=>{const form=e.target;if(!form.dataset.staffForm)return;e.preventDefault();if(!S.allowed())return;const data=Object.fromEntries(new FormData(form)),kind=form.dataset.staffForm;let error='';const submit=form.querySelector('button[type="submit"],button:not([type])');if(submit)submit.disabled=true;
 if(kind==='stock')error=S.saveError?'The stock update could not be saved.':I.change({id:form.dataset.id,quantity:Number(data.quantity),type:form.dataset.type,reason:data.reason,notes:data.notes,key:S.formKey});
 if(kind==='profile'){if(!data.first_name.trim()||!data.last_name.trim())error='Enter your first and last name.';else if(S.saveError)error='Your profile could not be saved.';else Object.assign(S.account,{first_name:data.first_name.trim(),last_name:data.last_name.trim()});}
 if(kind==='password')error=await S.password(data.current,data.next,data.confirm);
 if(submit)submit.disabled=false;if(!form.isConnected)return;if(error){form.querySelector('.staff-error').textContent=error;return;}if(kind==='stock')A.closeModal();else S.render();A.shell.sync();A.toast('Changes saved in this preview.');
});
})();
