
    tailwind.config = {
      darkMode: "class",
      theme: {
        extend: {
          "colors": {
            "inverse-primary": "#ffb786",
            "on-error": "#ffffff",
            "on-surface": "#1b1c1a",
            "primary": "#8d4a14",
            "inverse-surface": "#30312f",
            "primary-container": "#ab622b",
            "secondary-container": "#eae1dc",
            "primary-fixed": "#ffdcc6",
            "on-primary-container": "#fffbff",
            "on-primary-fixed": "#311300",
            "on-surface-variant": "#53443a",
            "surface-container-high": "#eae8e5",
            "surface-container-lowest": "#ffffff",
            "on-primary-fixed-variant": "#723600",
            "error-container": "#ffdad6",
            "surface-container": "#efeeeb",
            "surface-variant": "#e4e2df",
            "on-secondary": "#ffffff",
            "surface-container-highest": "#e4e2df",
            "surface-tint": "#904d16",
            "tertiary-container": "#7b736d",
            "outline-variant": "#d9c2b5",
            "on-secondary-fixed-variant": "#4b4642",
            "tertiary-fixed-dim": "#cfc5bd",
            "background": "#fbf9f6",
            "on-tertiary": "#ffffff",
            "surface-bright": "#fbf9f6",
            "tertiary-fixed": "#ebe0d9",
            "surface-dim": "#dbdad7",
            "on-background": "#1b1c1a",
            "on-tertiary-fixed": "#201b16",
            "on-error-container": "#93000a",
            "tertiary": "#625b55",
            "on-secondary-container": "#69635f",
            "secondary-fixed": "#eae1dc",
            "inverse-on-surface": "#f2f0ed",
            "primary-fixed-dim": "#ffb786",
            "secondary": "#635d59",
            "outline": "#867368",
            "secondary-fixed-dim": "#cdc5c0",
            "on-tertiary-container": "#fffbff",
            "error": "#ba1a1a",
            "surface": "#fbf9f6",
            "on-primary": "#ffffff",
            "on-tertiary-fixed-variant": "#4c4640",
            "surface-container-low": "#f5f3f0",
            "on-secondary-fixed": "#1f1b18"
          },
          "borderRadius": {
            "DEFAULT": "0.125rem",
            "lg": "0.25rem",
            "xl": "0.5rem",
            "full": "0.75rem"
          },
          "spacing": {
            "margin-mobile": "1.25rem",
            "gutter-mobile": "1rem",
            "space-sm": "0.5rem",
            "space-xl": "2.5rem",
            "margin": "3rem",
            "space-xs": "0.25rem",
            "space-lg": "1.5rem",
            "space-md": "1rem",
            "gutter": "1.5rem"
          },
          "fontFamily": {
            "price-lg": ["Plus Jakarta Sans"],
            "headline-lg": ["Playfair Display"],
            "display": ["Playfair Display"],
            "body-md": ["Plus Jakarta Sans"],
            "title-md": ["Plus Jakarta Sans"],
            "headline-sm": ["Playfair Display"],
            "body-sm": ["Plus Jakarta Sans"],
            "body-lg": ["Plus Jakarta Sans"],
            "headline-lg-mobile": ["Playfair Display"],
            "display-mobile": ["Playfair Display"],
            "price-md": ["Plus Jakarta Sans"],
            "headline-md": ["Playfair Display"],
            "title-sm": ["Plus Jakarta Sans"],
            "label-sm": ["Plus Jakarta Sans"],
            "label-md": ["Plus Jakarta Sans"]
          },
          "fontSize": {
            "price-lg": ["20px", { "lineHeight": "26px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
            "headline-lg": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.015em", "fontWeight": "500" }],
            "display": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "500" }],
            "body-md": ["14px", { "lineHeight": "22px", "fontWeight": "400" }],
            "title-md": ["16px", { "lineHeight": "24px", "letterSpacing": "-0.005em", "fontWeight": "600" }],
            "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "500" }],
            "body-sm": ["12px", { "lineHeight": "18px", "fontWeight": "400" }],
            "body-lg": ["16px", { "lineHeight": "26px", "fontWeight": "400" }],
            "headline-lg-mobile": ["26px", { "lineHeight": "34px", "letterSpacing": "-0.01em", "fontWeight": "500" }],
            "display-mobile": ["34px", { "lineHeight": "42px", "letterSpacing": "-0.01em", "fontWeight": "500" }],
            "price-md": ["15px", { "lineHeight": "20px", "fontWeight": "600" }],
            "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "500" }],
            "title-sm": ["14px", { "lineHeight": "20px", "fontWeight": "600" }],
            "label-sm": ["11px", { "lineHeight": "16px", "letterSpacing": "0.04em", "fontWeight": "600" }],
            "label-md": ["13px", { "lineHeight": "18px", "letterSpacing": "0.02em", "fontWeight": "600" }]
          }
        }
      }
    };
  