import EmbeddedPostgres from 'embedded-postgres';
import fs from 'node:fs';
import path from 'node:path';
import 'dotenv/config';
const url=new URL(process.env.DATABASE_URL);
const pg=new EmbeddedPostgres({databaseDir:path.resolve('.runtime/postgres'),user:url.username,password:url.password,port:Number(url.port),persistent:true,initdbFlags:['--encoding=UTF8','--set=dynamic_shared_memory_type=mmap','--set=shared_memory_type=mmap'],authMethod:'scram-sha-256',postgresFlags:['-h','127.0.0.1','-k','/tmp'],onLog:console.log,onError:console.error});
fs.mkdirSync('.runtime',{recursive:true});
if(!fs.existsSync('.runtime/postgres/PG_VERSION'))await pg.initialise();
await pg.start();
const c=pg.getPgClient();await c.connect();
if(!(await c.query('SELECT 1 FROM pg_database WHERE datname=$1',[url.pathname.slice(1)])).rowCount)await pg.createDatabase(url.pathname.slice(1));
await c.end();console.log('Kitchen406 PostgreSQL ready on loopback port '+url.port);
for(const sig of ['SIGINT','SIGTERM'])process.on(sig,async()=>{await pg.stop();process.exit(0)});
setInterval(()=>{},60000);
